/*
 * Curated public-information sample set for a portfolio prototype.
 * Snapshot: 2026-07-15. This file is intentionally conservative: data that
 * was not independently confirmed from an included public source is marked
 * unknown or needs verification instead of being inferred.
 */
(function () {
  const capturedAt = '2026-07-15';
  const source = (title, url, type = '公开来源') => ({ title, url, type, capturedAt });

  window.RADAR_DATA = {
    snapshot: {
      capturedAt,
      poolUpdatedAt: '2026-07-15 08:40',
      morningStatus: '已完成 · 本地样本刷新',
      eveningStatus: '待运行 · 不会自动联网',
      disclaimer: '作品集 Demo：样本来自有限公开来源；“更新样本”只重算本地数据，不代表实时抓取。'
    },
    projects: [
      {
        id: 'spine-ai',
        name: 'Spine AI',
        industry: 'Agent 基础设施',
        subSector: '多 Agent 编排',
        region: '北美',
        location: 'San Francisco, US',
        description: '可视化工作区：让多个 Agent 规划、分工并执行复杂任务，保留人类可审阅环节。',
        fullDescription: 'Spine AI 在公开 YC 页面中将自身描述为可视化多 Agent 工作区。用户从一个任务提示开始，Agent 以可见步骤协作、调用连接工具并输出可检查的中间结果。',
        product: '面向复杂知识工作的多 Agent 编排与可视化协作画布。',
        targetCustomers: '需要把研究、分析、内容或交付型工作流程交给 Agent 执行的团队。',
        aiApproach: '多 Agent 分工、模型路由、共享工作画布和人类在环审阅。',
        founders: 'Akshay Budhkar（CEO）、Ashwin Venkatesh Raman（CTO）',
        founderBackground: 'YC 资料称 Akshay 曾在 Georgian Partners、Scribd、FarmLogs；Ashwin 曾在 Instacart、AWS/Alexa、NVIDIA 与 Waterloo 学习/工作。',
        stage: '未知（当前收录来源未确认公开轮次）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开页面强调复杂工作流、可审计中间产物与多模型编排；客户与收入信息未在本次样本中核验。',
        competitors: '通用 Agent 编排、企业 AI 工作流、协作式研究工具。',
        relatedEvents: ['world-summit-ai', 'agent-craft'],
        publicContacts: [{ label: 'YC 公司页 / 公开联系入口', url: 'https://www.ycombinator.com/companies/spine-ai' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/spine-ai', 'YC 公开档案')],
        discoveredAt: '2026-07-15 07:48',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '来源页抓取时间以页面显示为准；本地样本于 2026-07-15 写入。',
        confidence: '高',
        confidenceNote: '产品、所在地与创始人背景均有 YC 公司档案佐证；融资信息保留未知。',
        score: { novelty: 4, source: 5, completeness: 4, relevance: 5, stage: 3, followup: 4 },
        why: ['多 Agent 编排是近期 AI 基础设施的持续主题。', '工作过程可审计，适合关注企业可信部署与人机协同的投资人。'],
        uncertainties: ['实际部署深度、客户留存及单位经济尚未核验。', '公开融资阶段与股权结构未知。'],
        verifyQuestions: ['首批付费客户来自哪些工作流？', '多模型路由带来的成本、延迟和质量提升如何量化？', '与通用 Agent 平台的迁移成本是什么？']
      },
      {
        id: 'raindrop',
        name: 'Raindrop',
        industry: 'Agent 基础设施',
        subSector: 'Agent 可观测性 / 质量监控',
        region: '北美',
        location: 'San Francisco, US',
        description: '为生产环境中的 AI Agent 发现静默失效、定位对话与工具调用问题。',
        fullDescription: 'YC 公司档案将 Raindrop 描述为“AI Agent 的 Sentry”：监控 AI 产品行为，针对异常发出告警，并把工程师带回对话和 trace 以定位根因。',
        product: 'Agent 运行监控、失败告警、生产数据检索与问题分类。',
        targetCustomers: '部署客服、工作流或内部 Copilot 的 AI 工程团队。',
        aiApproach: '基于生产对话与 trace 的故障检测、自然语言检索和少样本分类。',
        founders: 'Zubin Koticha、Ben Hylak',
        founderBackground: 'YC 资料称 Zubin 曾联合创办 Opyn；Ben 曾在 Apple Human Interface 团队工作。',
        stage: '未知（当前收录来源未确认公开轮次）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开页面称产品服务 AI 工程师；客户名单与商业化数据未在本次样本中验证。',
        competitors: 'LLM observability、Agent eval、线上质量监控工具。',
        relatedEvents: ['world-summit-ai', 'neurips-2026'],
        publicContacts: [{ label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/raindrop' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/raindrop', 'YC 公开档案')],
        discoveredAt: '2026-07-15 07:46',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '高',
        confidenceNote: '产品定位、所在地、两位创始人背景均有 YC 公开资料。',
        score: { novelty: 4, source: 5, completeness: 4, relevance: 5, stage: 3, followup: 4 },
        why: ['企业 Agent 从试点走向生产后，质量与可观测性是明确痛点。', '产品把“可解释、可验证”嵌入运维场景。'],
        uncertainties: ['告警准确率与噪声控制方式未公开验证。', '客户集中度和采购路径未知。'],
        verifyQuestions: ['核心付费场景是评测前置还是线上监控？', '如何与现有 trace / eval 工具集成？', '哪些失效类型最能体现 ROI？']
      },
      {
        id: 'hamming-ai',
        name: 'Hamming AI',
        industry: 'Voice AI',
        subSector: '语音 Agent 测试与分析',
        region: '北美',
        location: 'San Francisco, US',
        description: '面向 Voice Agent 的上线前测试与上线后质量分析平台。',
        fullDescription: 'Hamming AI 的 YC 资料将其定位为 voice agent 的完整 QA 平台，聚焦提示词、函数调用定义或模型供应商变化造成的质量波动。',
        product: '语音 Agent 的自动化测试、评测和上线后分析。',
        targetCustomers: '使用语音 Agent 提供客服、销售或运营服务的企业。',
        aiApproach: '用模拟对话和生产分析评估语音 Agent 的稳定性。',
        founders: 'Sumanyu Sharma、Marius（全名待核验）',
        founderBackground: 'YC 资料称 Sumanyu 曾在 Citizen、Tesla；其余创始信息需以公司或 YC 档案复核。',
        stage: '未知（当前收录来源未确认公开轮次）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开招聘页说明产品聚焦企业 Voice AI 质量；收入、客户与轮次未披露于当前证据。',
        competitors: '语音 Agent 平台内置测试、LLM eval、客服 QA 工具。',
        relatedEvents: ['superai-2026', 'world-summit-ai'],
        publicContacts: [{ label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/hamming-ai' }, { label: '公司官网', url: 'https://hamming.ai/' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/hamming-ai', 'YC 公开档案'), source('公司官网', 'https://hamming.ai/', '官网')],
        discoveredAt: '2026-07-15 07:42',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品与公司基础信息有公开来源；创始团队完整信息和融资信息需要人工复核。',
        needsManualReview: true,
        score: { novelty: 4, source: 4, completeness: 3, relevance: 5, stage: 3, followup: 4 },
        why: ['Voice Agent 商业化加速时，质量保证通常成为关键配套层。', '从“是否能跑”转向“是否可靠”的工具链值得跟踪。'],
        uncertainties: ['创始团队信息未完整确认。', '目标客户是否集中于特定垂直行业未知。'],
        verifyQuestions: ['模拟测试与真实通话分析的覆盖差异？', '评测指标是否与业务结果挂钩？', '客户的替代方案是什么？']
      },
      {
        id: 'vapi',
        name: 'Vapi',
        industry: 'Voice AI',
        subSector: '开发者语音 Agent 平台',
        region: '北美',
        location: 'San Francisco, US',
        description: '帮助开发者构建、测试和部署语音 AI 产品的 API 平台。',
        fullDescription: 'YC 公开档案将 Vapi 定位为 “Voice AI for developers”，并列出其作为活跃的人工智能公司及两位创始人。',
        product: '语音 Agent 的开发者 API 与平台能力。',
        targetCustomers: '需要把语音交互接入应用、客服或运营流程的开发团队。',
        aiApproach: '语音识别、语音合成、对话编排与模型/工具调用集成。',
        founders: 'Jordan Dearsley（CEO）、Nikhil Gupta（CTO）',
        founderBackground: '创始人角色来自 YC 公司档案；进一步履历需单独核验。',
        stage: '未知（媒体估值报道未作为本样本正式融资结论）',
        amount: '未知',
        valuation: '未知（需直接查验融资公告）',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '存在开发者生态与招聘信息；实际付费结构、留存和毛利未在当前来源中验证。',
        competitors: '语音 Agent 平台、通信 API、全栈客服自动化工具。',
        relatedEvents: ['superai-2026', 'world-summit-ai'],
        publicContacts: [{ label: '公司官网', url: 'https://vapi.ai/' }, { label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/vapi' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/vapi', 'YC 公开档案'), source('Vapi 官网', 'https://vapi.ai/', '官网')],
        discoveredAt: '2026-07-15 07:39',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '高',
        confidenceNote: '产品、所在地、创始人职位与 YC 档案一致；融资字段保持未知。',
        score: { novelty: 3, source: 5, completeness: 4, relevance: 5, stage: 3, followup: 4 },
        why: ['语音交互是 Agent 进入电话、销售和客服工作流的重要入口。', '开发者 API 更容易观察生态、调用量和垂直落地。'],
        uncertainties: ['竞争壁垒与底层模型供应依赖待确认。', '高并发语音成本与客户留存未知。'],
        verifyQuestions: ['客户主要自建体验还是购买完整应用？', '平台的质量、延迟和成本指标如何披露？', '是否出现明确的行业 solution wedge？']
      },
      {
        id: 'rhizome-ai',
        name: 'Rhizome AI',
        industry: 'AI for Life Sciences',
        subSector: '监管情报 Agent',
        region: '北美',
        location: 'New York City, US',
        description: '让生命科学团队用可引用的 Agent 查询 FDA 监管与临床资料。',
        fullDescription: 'YC 档案称 Rhizome AI 的研究 Agent 可在监管和临床文档中检索，并为回答提供引用；产品面向生命科学公司的监管与研发工作。',
        product: '面向生命科学监管工作的带引用检索与研究 Agent。',
        targetCustomers: '药企、医疗器械与生命科学公司的监管事务、R&D 团队。',
        aiApproach: '垂直数据集检索、可引用回答和领域工作流 Agent。',
        founders: 'Chetan（姓氏待公开资料复核）',
        founderBackground: 'YC 页面称其曾在 EvolutionaryScale 担任早期产品工程角色；完整姓名与股权团队待核验。',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '可能（YC W26；不以批次替代融资判断）',
        commercial: '垂直场景、强检索与合规需求形成明确问题切口；付费客户与合同周期未公开核验。',
        competitors: '生命科学信息服务、垂直 RAG、监管咨询与内部知识库。',
        relatedEvents: ['ai-for-good-2026', 'world-summit-ai'],
        publicContacts: [{ label: '公司官网', url: 'https://rhizomeai.com/' }, { label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/rhizome-ai' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/rhizome-ai', 'YC 公开档案')],
        discoveredAt: '2026-07-15 07:34',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品方向和所在地有公开依据；团队、商业化和融资信息需人工验证。',
        needsManualReview: true,
        score: { novelty: 5, source: 4, completeness: 3, relevance: 4, stage: 4, followup: 5 },
        why: ['在高监管行业，带证据的 Agent 比泛用聊天工具更有可验证价值。', '明确垂直工作流有助于验证付费意愿和数据壁垒。'],
        uncertainties: ['医疗/监管数据授权范围与责任边界未知。', '创始人和商业数据仍需二次核验。'],
        verifyQuestions: ['引用质量和监管团队采纳率如何评估？', '数据覆盖是否可跨地区扩展？', '产品的合规责任由谁承担？']
      },
      {
        id: 'broccoli-ai',
        name: 'Broccoli AI',
        industry: 'Vertical AI',
        subSector: '家庭服务行业 AI 操作系统',
        region: '北美',
        location: 'San Francisco, US',
        description: '为管道、HVAC 等家庭服务商自动处理接听、排班、跟进和运营。',
        fullDescription: 'YC 资料称 Broccoli 正在为家庭服务企业建设 AI-native 操作系统：Agent 处理电话、实时预约、线索跟进和紧急提醒。',
        product: '家庭服务商的语音 Agent、调度、客户关系与运营自动化。',
        targetCustomers: '管道、HVAC 等线下家庭服务企业。',
        aiApproach: '语音 Agent 与行业运营系统联动，覆盖获客和运营环节。',
        founders: 'AJ、Adi（公开资料中的全名需二次核验）',
        founderBackground: 'YC 页面称两位创始人已合作多年，AJ 有 Adobe 和连续创业经历。',
        stage: 'Series A（YC 页面称由 Khosla Ventures 领投；金额待核验）',
        amount: '未知',
        valuation: '未知',
        lastFunding: 'Series A 公告日期待核验',
        bBefore: '是（基于 YC 页面中 Series A 表述；需复核公告）',
        commercial: 'YC 页面称其已服务 800+ contractors（公司自述，未独立验证）。',
        competitors: '家庭服务 SaaS、呼叫中心、垂直 CRM 与语音自动化。',
        relatedEvents: ['world-summit-ai', 'ai-summit-london'],
        publicContacts: [{ label: '公司官网', url: 'https://www.broccoli.com/' }, { label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/broccoli-ai' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/broccoli-ai', 'YC 公开档案')],
        discoveredAt: '2026-07-15 07:29',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '赛道、产品描述与 Series A 自述有公开依据；金额、客户和团队完整身份需复核。',
        score: { novelty: 4, source: 4, completeness: 4, relevance: 4, stage: 5, followup: 5 },
        why: ['高频电话与排班工作流具备明确自动化价值。', '垂直领域可同时观察获客、运营和收入增长闭环。'],
        uncertainties: ['客户数为公司自述。', '跨城市、跨行业复制与实施成本待验证。'],
        verifyQuestions: ['收入来自订阅、按通话还是按成交？', '语音 Agent 的转化率如何与人工比较？', '与现有 FSM 软件的集成深度？']
      },
      {
        id: 'tasklet',
        name: 'Tasklet',
        industry: 'Agent 应用',
        subSector: '知识工作 Agent',
        region: '北美',
        location: 'San Francisco, US（待核验）',
        description: '面向知识工作的云端 Agent，强调让 Agent “拥有工作”而非只提供回答。',
        fullDescription: 'YC 页面介绍 Tasklet 从原有产品转向独立云端知识工作 Agent；该记录只保留公开页面所述定位，不推断其实际客户或融资情况。',
        product: '独立云端知识工作 Agent。',
        targetCustomers: '有重复分析、协调或后台知识工作需求的团队。',
        aiApproach: '云端 Agent 执行多步骤知识工作。',
        founders: '待公开资料核验',
        founderBackground: '待核验',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '当前收录来源主要为产品叙述；客户、收入、轮次均未确认。',
        competitors: '通用工作 Agent、自动化平台、企业 Copilot。',
        relatedEvents: ['agent-craft', 'world-summit-ai'],
        publicContacts: [{ label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/tasklet-2' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/tasklet-2', 'YC 公开档案')],
        discoveredAt: '2026-07-14 21:10',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '低',
        confidenceNote: '仅收录到公开产品叙述；团队、所在地、融资与真实落地需人工核验。',
        needsManualReview: true,
        score: { novelty: 4, source: 3, completeness: 2, relevance: 5, stage: 3, followup: 3 },
        why: ['“承担工作”而非“聊天回答”的产品叙事值得跟踪。', '但当前证据不足，不应据此做投资判断。'],
        uncertainties: ['团队、客户、产品边界、数据与安全机制均待核验。'],
        verifyQuestions: ['具体拥有哪类工作流的端到端责任？', '人类如何审批或撤销动作？', '产品是否有可量化的客户结果？']
      },
      {
        id: 'superagent',
        name: 'Superagent',
        industry: 'AI 安全',
        subSector: 'Agent 红队测试',
        region: '北美',
        location: 'San Francisco, US',
        description: '通过专用攻击 Agent 对生产 Agent 做数据泄漏、有害输出和越权测试。',
        fullDescription: 'YC 页面将 Superagent 定位为“Agent 的红队测试”：用专门的攻击 Agent 扫描生产系统中的数据泄露、有害输出和非预期动作。',
        product: '面向企业 AI Agent 的安全测试、报告与采购证明材料。',
        targetCustomers: '向企业或受监管行业销售 AI Agent 的开发团队。',
        aiApproach: '攻击 Agent、自动化安全测试与结构化风险报告。',
        founders: 'Alan、Ismail（姓氏待核验）',
        founderBackground: 'YC 档案称二人为创始人；进一步背景需要直接来源验证。',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开定位面向企业与受监管客户；当前样本未验证付费客户。',
        competitors: 'AI red teaming、模型安全评估、应用安全工具。',
        relatedEvents: ['world-summit-ai', 'neurips-2026'],
        publicContacts: [{ label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/superagent' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/superagent', 'YC 公开档案')],
        discoveredAt: '2026-07-14 20:56',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品方向与所在地有公开来源；商业进度和融资信息未验证。',
        score: { novelty: 5, source: 4, completeness: 3, relevance: 5, stage: 3, followup: 4 },
        why: ['企业采购越来越要求 AI 安全与可验证控制。', '将红队能力产品化有明确的切入点。'],
        uncertainties: ['红队覆盖率和误报率未公开。', '是否能进入现有安全预算待验证。'],
        verifyQuestions: ['攻击库如何持续更新？', '与传统 AppSec 的采购方是否相同？', '是否提供持续监控而非一次性测试？']
      },
      {
        id: 'origami-agents',
        name: 'Origami Agents',
        industry: 'Sales AI',
        subSector: '销售研究 Agent',
        region: '北美',
        location: 'San Francisco, US',
        description: '用研究 Agent 加速 B2B 销售线索研究与外联准备。',
        fullDescription: 'YC 页面称 Origami Agents 为销售团队提供研究 Agent，以加快 outbound pipeline 的研究和准备工作。',
        product: 'B2B outbound 的账户研究、线索准备与工作流自动化。',
        targetCustomers: '依赖销售开发和账号研究的 B2B 团队。',
        aiApproach: '多源公开信息研究与销售工作流自动化。',
        founders: '待公开资料核验',
        founderBackground: '待核验',
        stage: 'Seed（YC 页面新闻转引 US$2m；未作为独立融资公告验证）',
        amount: 'US$2m（转引，待核验）',
        valuation: '未知',
        lastFunding: '日期待核验',
        bBefore: '可能（基于 Seed 转引）',
        commercial: 'YC 页面称其服务 Rho、Redesign Health、Remote.com 等；均为公司页面自述，需独立验证。',
        competitors: '销售情报、AI SDR、CRM enrichment、研究 Agent。',
        relatedEvents: ['ai-summit-london', 'world-summit-ai'],
        publicContacts: [{ label: 'YC 公司页', url: 'https://www.ycombinator.com/companies/origami-agents' }],
        sources: [source('Y Combinator 公司档案', 'https://www.ycombinator.com/companies/origami-agents', 'YC 公开档案')],
        discoveredAt: '2026-07-14 20:31',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品方向和公司自述有公开来源；融资金额与客户必须二次核验。',
        score: { novelty: 3, source: 4, completeness: 3, relevance: 4, stage: 5, followup: 4 },
        why: ['销售场景有明确可量化产出，适合验证 Agent 的真实 ROI。', '可对照传统数据服务和 AI SDR 的差异。'],
        uncertainties: ['客户名单、融资金额均为转引或公司自述。', '数据合规和 outbound 质量待验证。'],
        verifyQuestions: ['研究结果如何影响转化率？', '产品边界是研究、内容生成还是自动触达？', '如何确保公开数据的合规与准确性？']
      },
      {
        id: 'manus',
        name: 'Manus',
        industry: 'Agent 应用',
        subSector: '通用自主 Agent',
        region: '全球',
        location: '待公开资料核验',
        description: '通用型任务执行 Agent；本样本只记录公开产品入口，不对公司主体、融资或所在地作推断。',
        fullDescription: 'Manus 提供面向复杂任务执行的 Agent 产品入口。由于当前样本未纳入可核验的公司主体和融资公告，详细实体关系保留待验证。',
        product: '通用任务执行 Agent。',
        targetCustomers: '个人和团队用户（具体付费客群待核验）。',
        aiApproach: '多步骤任务规划、工具使用与交付物生成（以产品公开展示为准）。',
        founders: '未知 / 待核验',
        founderBackground: '未知 / 待核验',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开产品入口存在；公司主体、客户和收入数据未在本样本中验证。',
        competitors: '通用 Agent、浏览器 Agent、深度研究和自动化工具。',
        relatedEvents: ['agent-craft', 'world-summit-ai'],
        publicContacts: [{ label: '产品官网', url: 'https://manus.im/' }],
        sources: [source('Manus 产品官网', 'https://manus.im/', '官网')],
        discoveredAt: '2026-07-15 07:20',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '低',
        confidenceNote: '只确认了公开产品入口；主体、团队、轮次和联系渠道均需人工核验。',
        needsManualReview: true,
        score: { novelty: 5, source: 2, completeness: 2, relevance: 5, stage: 3, followup: 3 },
        why: ['通用 Agent 的产品体验与分发路径值得观察。', '但该记录当前仅适合作为待研究线索。'],
        uncertainties: ['公司主体、团队、融资、真实用户结构与安全边界均未知。'],
        verifyQuestions: ['公司主体和创始团队是谁？', '任务成功率、成本与用户留存如何衡量？', '哪些垂直工作流形成了可重复价值？']
      },
      {
        id: 'genspark',
        name: 'Genspark',
        industry: 'Agent 应用',
        subSector: 'AI 搜索与工作流 Agent',
        region: '北美',
        location: '待公开资料核验',
        description: '以 AI 搜索和 Agent 工作流为主的产品；当前样本只保留官网公开表述。',
        fullDescription: 'Genspark 的官网提供 AI 搜索与 Agent 产品入口。本样本不把媒体报道或社区转述当作融资、估值或团队结论。',
        product: 'AI 搜索、信息整理与任务型 Agent。',
        targetCustomers: '需要研究、比较或生成交付物的知识工作用户。',
        aiApproach: '搜索、信息汇总和 Agent 工作流。',
        founders: '未知 / 待核验',
        founderBackground: '未知 / 待核验',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开产品入口存在；付费策略与企业客户待验证。',
        competitors: 'AI 搜索、研究 Agent、通用工作流 Agent。',
        relatedEvents: ['agent-craft', 'ai-summit-london'],
        publicContacts: [{ label: '产品官网', url: 'https://www.genspark.ai/' }],
        sources: [source('Genspark 产品官网', 'https://www.genspark.ai/', '官网')],
        discoveredAt: '2026-07-15 07:17',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '低',
        confidenceNote: '产品入口可公开访问；公司与融资信息未在本样本的来源中验证。',
        needsManualReview: true,
        score: { novelty: 4, source: 2, completeness: 2, relevance: 5, stage: 3, followup: 3 },
        why: ['AI 搜索正在向可交付结果的工作流演进。', '需要验证产品是否形成长期使用与分发优势。'],
        uncertainties: ['公司主体、团队、商业化、数据来源和合规能力未知。'],
        verifyQuestions: ['目标用户是谁，核心留存动作是什么？', '与通用搜索/研究产品的差异？', '生成结果的可验证性如何保障？']
      },
      {
        id: 'lovable',
        name: 'Lovable',
        industry: 'AI 开发工具',
        subSector: '自然语言应用构建',
        region: '欧洲',
        location: 'Stockholm, Sweden（待官网资料复核）',
        description: '让用户用自然语言构建和迭代 Web 应用的 AI 产品。',
        fullDescription: 'Lovable 的公开产品网站展示了通过自然语言创建应用的工作流。该记录用于跟踪 AI 应用构建产品，不将未收录的融资新闻写入字段。',
        product: '从自然语言需求到可运行应用的生成式开发产品。',
        targetCustomers: '创始人、产品团队、设计师与非传统开发者。',
        aiApproach: '代码生成、组件组合、应用预览和迭代。',
        founders: 'Anton Osika（具体角色和团队需二次核验）',
        founderBackground: '待官网或权威公开资料复核。',
        stage: '未知（当前收录来源未确认）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开产品可试用；商业化与客户结构未在此样本验证。',
        competitors: 'AI IDE、应用生成、低代码/无代码平台。',
        relatedEvents: ['world-summit-ai', 'ai-summit-london'],
        publicContacts: [{ label: '公司官网', url: 'https://lovable.dev/' }],
        sources: [source('Lovable 产品官网', 'https://lovable.dev/', '官网')],
        discoveredAt: '2026-07-14 19:42',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品功能有公开入口；团队、地点、融资和企业留存应人工核验。',
        score: { novelty: 4, source: 3, completeness: 3, relevance: 5, stage: 3, followup: 4 },
        why: ['AI 改变了从需求到原型的交付速度。', '可直接观察产品的协作、质量与分发能力。'],
        uncertainties: ['从原型到生产的质量和安全性待验证。', '用户群与付费路径未知。'],
        verifyQuestions: ['非技术用户能否交付真实业务应用？', '生成代码的可维护性如何？', '留存来自个人订阅还是团队协作？']
      },
      {
        id: 'cursor',
        name: 'Cursor / Anysphere',
        industry: 'AI 开发工具',
        subSector: 'AI 编程环境',
        region: '北美',
        location: 'San Francisco, US（待二次核验）',
        description: '以 AI 辅助编程为核心的代码编辑器与开发工作流。',
        fullDescription: 'Cursor 的公开产品网站展示 AI 参与代码理解、生成和编辑的工作流。本样本将其作为 AI-native 开发工具的成熟对照样本，不把轮次与估值用作筛选结论。',
        product: 'AI code editor / coding agent 工作流。',
        targetCustomers: '软件工程师与产品开发团队。',
        aiApproach: '代码上下文理解、自然语言编辑、Agent 式开发协作。',
        founders: 'Michael Truell 等（完整团队与背景待核验）',
        founderBackground: '待官网或权威公开资料复核。',
        stage: '未知（当前样本未录入融资公告）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '否 / 不作为早期项目筛选标的（需融资资料确认）',
        commercial: '产品拥有公开可用入口；收入、客户和融资不在本样本中作结论。',
        competitors: 'AI IDE、编码 Agent、代码托管平台的原生 AI 功能。',
        relatedEvents: ['agent-craft', 'world-summit-ai'],
        publicContacts: [{ label: 'Cursor 官网', url: 'https://www.cursor.com/' }],
        sources: [source('Cursor 产品官网', 'https://www.cursor.com/', '官网')],
        discoveredAt: '2026-07-14 19:30',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品存在与定位有公开入口；公司、融资与团队细节需单独验证。',
        score: { novelty: 3, source: 3, completeness: 3, relevance: 5, stage: 1, followup: 3 },
        why: ['作为对照样本，可帮助判断“Agent 真的进入工作流”需要哪些体验与分发能力。', '不代表适合早期投资。'],
        uncertainties: ['融资阶段和估值未收录；不应由系统猜测。'],
        verifyQuestions: ['核心护城河在模型、上下文还是产品体验？', '团队版的采购与扩张路径？', '与基础模型供应商的依赖程度？']
      },
      {
        id: 'decagon',
        name: 'Decagon',
        industry: 'Customer Service AI',
        subSector: '客户体验 Agent',
        region: '北美',
        location: 'San Francisco, US（待二次核验）',
        description: '面向客户服务的对话式 AI Agent，覆盖文字和语音交互。',
        fullDescription: 'Decagon 官方关于页面描述其为客户体验场景的对话式 AI，并发布 AI Voice Agents。',
        product: '客服对话、语音 Agent 与企业客户体验自动化。',
        targetCustomers: '希望自动化客服与支持流程的中大型企业。',
        aiApproach: '对话式 Agent、语音 Agent、企业知识与系统集成。',
        founders: 'Jesse Zhang、Ashwin Sreenivas（待官网资料复核）',
        founderBackground: '待官方或权威公开资料复核。',
        stage: '未知（本样本不采用未验证新闻作为轮次）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '客户体验是明确企业预算场景；官网未在本样本中提供可复核的收入信息。',
        competitors: '客服 SaaS、BPO、客服 Agent 与语音自动化平台。',
        relatedEvents: ['ai-summit-london', 'superai-2026'],
        publicContacts: [{ label: '公司关于页', url: 'https://decagon.ai/about' }],
        sources: [source('Decagon 官网', 'https://decagon.ai/about', '官网')],
        discoveredAt: '2026-07-14 19:18',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品定位有官方来源；团队、客户、融资与地区需下一轮证据补全。',
        score: { novelty: 4, source: 3, completeness: 3, relevance: 5, stage: 3, followup: 4 },
        why: ['客服是企业 AI 落地中最易量化的高频场景之一。', '语音能力可拓展到复杂服务流程。'],
        uncertainties: ['自动化率、升级人工比例与客户 ROI 未公开验证。'],
        verifyQuestions: ['是否进入核心客服系统而非边缘 FAQ？', '模型错误怎样被识别和回滚？', '客户采购决定者与销售周期？']
      },
      {
        id: 'harvey',
        name: 'Harvey',
        industry: 'Vertical AI',
        subSector: '法律与专业服务 AI',
        region: '北美',
        location: '待官网公开资料复核',
        description: '为法律和专业服务团队提供领域专用 AI。',
        fullDescription: 'Harvey 公司页面称其为法律和专业服务领域的 domain-specific AI，并展示了客户和投资方信息。该记录仅用作垂直 AI 商业化对照，不建议按排名直接判断投资价值。',
        product: '法律与专业服务的领域专用 AI 工作流。',
        targetCustomers: '律所、企业法务与专业服务机构。',
        aiApproach: '面向法律任务的领域适配模型、工作流与企业产品。',
        founders: 'Winston Weinberg、Gabe Pereyra（待二次核验）',
        founderBackground: '创始团队信息需从公司或权威公开资料进行复核。',
        stage: '后期私营公司（准确轮次需查融资公告）',
        amount: '未知（本样本不录入未验证金额）',
        valuation: '未知（本样本不录入未验证估值）',
        lastFunding: '未知',
        bBefore: '否 / 不以早期项目跟进为主',
        commercial: '公司页面称服务 2,400+ 客户、70+ 国家（公司自述，未独立验证）。',
        competitors: '法律信息服务、法务 SaaS、专业服务 AI。',
        relatedEvents: ['ai-summit-london', 'world-summit-ai'],
        publicContacts: [{ label: '公司页', url: 'https://www.harvey.ai/company' }],
        sources: [source('Harvey 公司页', 'https://www.harvey.ai/company', '官网')],
        discoveredAt: '2026-07-14 18:52',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '高',
        confidenceNote: '领域定位和公司自述客户规模来自官方页面；融资字段故意不作推断。',
        score: { novelty: 3, source: 4, completeness: 4, relevance: 4, stage: 1, followup: 2 },
        why: ['展示垂直 AI 如何进入高价值、强流程的专业服务。', '适合作为商业化和客户价值的对照研究。'],
        uncertainties: ['官方客户统计未独立核验。', '不是典型早期项目线索。'],
        verifyQuestions: ['领域数据、工作流与服务网络各自构成何种壁垒？', '客户扩张能否从律所进入企业法务？']
      },
      {
        id: 'abridge',
        name: 'Abridge',
        industry: 'Healthcare AI',
        subSector: '临床文档与临床决策支持',
        region: '北美',
        location: 'Pittsburgh, US（待二次核验）',
        description: '把临床对话转化为文档和上下文支持，面向医疗系统。',
        fullDescription: 'Abridge 官方关于页面称其使命是利用 AI 增进医疗理解，产品覆盖临床文档、收入周期、护理和临床决策支持。',
        product: '临床环境的对话记录、文档、编码和决策支持产品。',
        targetCustomers: '医疗系统、临床医生、护理与收入周期团队。',
        aiApproach: '医学语音/文本理解、上下文推理与临床工作流集成。',
        founders: 'Shiv Rao, MD（CEO、Founder）',
        founderBackground: '公司官方关于页列示 Shiv Rao 为 CEO、Founder。',
        stage: '未知（本样本未录入融资公告）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '官网列示医疗系统客户故事与产品线；营收、合同和融资需直接来源验证。',
        competitors: '医疗记录、ambient AI、医疗信息系统与临床 AI。',
        relatedEvents: ['ai-for-good-2026', 'world-summit-ai'],
        publicContacts: [{ label: '公司关于页', url: 'https://www.abridge.com/about' }],
        sources: [source('Abridge 官方关于页', 'https://www.abridge.com/about', '官网')],
        discoveredAt: '2026-07-14 18:41',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '高',
        confidenceNote: '产品线、客户类型与创始人角色都来自官方页面；融资、估值保持未知。',
        score: { novelty: 4, source: 5, completeness: 4, relevance: 4, stage: 3, followup: 4 },
        why: ['医疗是最要求准确性、合规与工作流嵌入的 AI 场景之一。', '临床对话到文档的价值链较清晰。'],
        uncertainties: ['临床效果、客户续约和责任边界需独立验证。'],
        verifyQuestions: ['如何测量准确率、医生信任与时间节省？', '与 EHR 的集成成本和复制性？', '临床决策支持的合规审批边界？']
      },
      {
        id: 'mistral-ai',
        name: 'Mistral AI',
        industry: '基础模型',
        subSector: '开放与企业生成式 AI',
        region: '欧洲',
        location: 'Paris, France（待二次核验）',
        description: '开发开放和企业可用的生成式 AI 模型与产品。',
        fullDescription: 'Mistral 的公开资料将其定位为生成式 AI 公司，提供模型和面向企业的 AI 能力。本记录用于观察欧洲模型与企业部署生态，不是早期项目推荐。',
        product: '基础模型、部署与企业生成式 AI 产品。',
        targetCustomers: '开发者、企业与需要模型部署选择的机构。',
        aiApproach: '大语言模型、开放模型与企业部署能力。',
        founders: 'Arthur Mensch、Guillaume Lample、Timothée Lacroix（待二次核验）',
        founderBackground: '需要以公司介绍或权威公开资料复核。',
        stage: '后期私营公司（当前样本不录入轮次）',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '否 / 不以早期项目跟进为主',
        commercial: '模型和企业产品公开可访问；收入、客户与融资信息不在本样本作结论。',
        competitors: '基础模型公司、云模型平台、企业模型部署工具。',
        relatedEvents: ['world-summit-ai', 'neurips-2026'],
        publicContacts: [{ label: '公司官网', url: 'https://mistral.ai/' }],
        sources: [source('Mistral AI 官网', 'https://mistral.ai/', '官网')],
        discoveredAt: '2026-07-14 18:22',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '公司产品方向有公开资料；所有团队、融资和估值字段须单独验证。',
        score: { novelty: 3, source: 3, completeness: 3, relevance: 5, stage: 1, followup: 2 },
        why: ['模型层的开放策略、企业部署与生态路线值得研究。', '更适合作为产业跟踪与活动线索。'],
        uncertainties: ['轮次、估值和商业指标未收录。'],
        verifyQuestions: ['开放模型与企业产品的价值分配？', '区域主权 AI 需求带来何种差异化？']
      },
      {
        id: 'dust',
        name: 'Dust',
        industry: 'Enterprise AI',
        subSector: '企业知识 Agent',
        region: '欧洲',
        location: 'Paris, France（待二次核验）',
        description: '为企业团队提供可连接内部知识与工具的 AI Agent。',
        fullDescription: 'Dust 公开产品网站展示企业 AI Agent 与工作空间能力；该样本不把非官方融资传闻写入字段。',
        product: '连接企业知识、应用和工具的可配置 AI Agent。',
        targetCustomers: '希望在内部知识和业务工具之上部署 AI 的企业团队。',
        aiApproach: '企业数据连接、Agent 配置、模型调用与权限控制。',
        founders: 'Stan Polu 等（待二次核验）',
        founderBackground: '待公司/权威公开资料确认。',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '产品可公开查看；企业客户、部署规模和融资未在样本中确认。',
        competitors: '企业知识库、RAG 平台、企业 Agent 与协作软件 AI。',
        relatedEvents: ['world-summit-ai', 'ai-summit-london'],
        publicContacts: [{ label: '公司官网', url: 'https://dust.tt/' }],
        sources: [source('Dust 官网', 'https://dust.tt/', '官网')],
        discoveredAt: '2026-07-14 18:08',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品入口存在；实体信息、轮次和客户案例需要进一步佐证。',
        score: { novelty: 4, source: 3, completeness: 3, relevance: 5, stage: 3, followup: 4 },
        why: ['企业知识、权限和业务工具连接是 Agent 落地的核心难题。', '可以研究自助式产品与企业销售的结合。'],
        uncertainties: ['数据权限、安全审计和企业续约需验证。'],
        verifyQuestions: ['如何在权限模型中避免越权？', '产品扩张来自员工自助还是 IT 采购？', '模型切换和成本治理如何做？']
      },
      {
        id: 'baseten',
        name: 'Baseten',
        industry: 'AI 基础设施',
        subSector: '模型推理与部署',
        region: '北美',
        location: 'San Francisco, US（待二次核验）',
        description: '为模型提供训练后推理、部署和性能优化能力。',
        fullDescription: 'Baseten 官网展示模型部署和推理基础设施能力。该项目在 Demo 中用于观察 AI 应用爆发后对性能、成本和可靠部署的需求。',
        product: '模型推理、部署、性能优化和生产运营平台。',
        targetCustomers: '需要把生成式模型上线到生产环境的开发与企业团队。',
        aiApproach: '模型推理优化、部署编排、自动扩缩容和开发者平台。',
        founders: 'Tuhin Srivastava 等（待二次核验）',
        founderBackground: '待公司或权威公开资料确认。',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公司提供公开产品入口；客户与收入规模不在当前样本确认范围。',
        competitors: '云推理平台、模型托管、GPU 云和企业 MLOps。',
        relatedEvents: ['gtc-2026', 'world-summit-ai'],
        publicContacts: [{ label: '公司官网', url: 'https://www.baseten.co/' }],
        sources: [source('Baseten 官网', 'https://www.baseten.co/', '官网')],
        discoveredAt: '2026-07-14 17:54',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品方向有官方来源；融资、团队与客户信息未在此样本验证。',
        score: { novelty: 3, source: 3, completeness: 3, relevance: 5, stage: 3, followup: 3 },
        why: ['推理成本、延迟与可靠性决定许多 AI 产品的单位经济。', '基础设施层可补足应用层视角。'],
        uncertainties: ['差异化、毛利和客户集中度未知。'],
        verifyQuestions: ['优化带来多少实际成本/延迟改善？', '开发者自助和企业销售各占多少？', '与云厂商的合作/竞争关系？']
      },
      {
        id: 'cartesia',
        name: 'Cartesia',
        industry: 'Voice AI',
        subSector: '低延迟语音模型',
        region: '北美',
        location: '待公开资料核验',
        description: '提供面向实时交互的语音生成模型与开发者能力。',
        fullDescription: 'Cartesia 的公开网站展示实时语音生成和 API 产品。该线索与语音 Agent 生态相关，但团队、轮次和客户信息未在当前样本中确认。',
        product: '实时语音生成模型与开发者 API。',
        targetCustomers: '构建语音 Agent、互动内容和实时应用的开发团队。',
        aiApproach: '低延迟语音生成与模型 API。',
        founders: '未知 / 待核验',
        founderBackground: '未知 / 待核验',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '有公开产品入口；客户、轮次和真实使用量需人工核验。',
        competitors: '语音模型、语音 API、全栈语音 Agent 平台。',
        relatedEvents: ['superai-2026', 'world-summit-ai'],
        publicContacts: [{ label: '公司官网', url: 'https://cartesia.ai/' }],
        sources: [source('Cartesia 官网', 'https://cartesia.ai/', '官网')],
        discoveredAt: '2026-07-14 17:39',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '低',
        confidenceNote: '只确认产品公开入口；实体、团队、融资和客户均需补充证据。',
        needsManualReview: true,
        score: { novelty: 4, source: 2, completeness: 2, relevance: 4, stage: 3, followup: 3 },
        why: ['低延迟是语音 Agent 体验和商业化的底层约束。', '与应用层 Voice AI 项目形成可比较的技术栈。'],
        uncertainties: ['产品性能、客户采用和商业化完全待验证。'],
        verifyQuestions: ['延迟、音色和成本指标是什么？', '开发者在何种场景真正付费？', '模型与平台的边界在哪里？']
      },
      {
        id: 'pika',
        name: 'Pika',
        industry: '生成式内容',
        subSector: 'AI 视频生成',
        region: '北美',
        location: '待公开资料核验',
        description: '面向创作者的 AI 视频生成产品。',
        fullDescription: 'Pika 的公开产品页面展示文字、图片等输入到生成视频的工作流。本记录用于跟踪生成式内容的用户体验与商业化路径。',
        product: 'AI 视频生成与创作工具。',
        targetCustomers: '内容创作者、品牌、营销和创意团队。',
        aiApproach: '生成式视频模型与创作编辑工作流。',
        founders: 'Demi Guo、Chenlin Meng（待二次核验）',
        founderBackground: '待公司或权威公开资料确认。',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开产品可访问；订阅、企业客户与融资不在本样本作结论。',
        competitors: '生成式视频工具、创意软件和基础模型产品。',
        relatedEvents: ['metamorph-2026', 'world-summit-ai'],
        publicContacts: [{ label: '产品官网', url: 'https://pika.art/' }],
        sources: [source('Pika 产品官网', 'https://pika.art/', '官网')],
        discoveredAt: '2026-07-14 17:21',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品入口可公开访问；团队、融资和商业化数据需独立核验。',
        score: { novelty: 3, source: 3, completeness: 3, relevance: 4, stage: 3, followup: 3 },
        why: ['视频生成的创作成本与质量提升仍值得跟踪。', '可通过创作者留存、内容分发与企业工作流验证价值。'],
        uncertainties: ['版权、获客成本和模型迭代节奏待验证。'],
        verifyQuestions: ['用户价值来自娱乐创作还是商业制作？', '如何解决版权、品牌一致性和可控性？']
      },
      {
        id: 'luma-ai',
        name: 'Luma AI',
        industry: '生成式内容',
        subSector: '3D / 视频生成',
        region: '北美',
        location: '待公开资料核验',
        description: '提供生成式视频与 3D 内容创作能力。',
        fullDescription: 'Luma AI 的官网提供生成式视觉与 3D 产品入口。本样本仅基于公开产品信息整理，不推断融资与估值。',
        product: '生成式视频、3D 捕捉/生成和创作工具。',
        targetCustomers: '创作者、影视/广告团队、3D 与内容生产者。',
        aiApproach: '视觉生成、3D 重建与创作工具链。',
        founders: 'Amit Jain（待二次核验）',
        founderBackground: '待公司或权威公开资料确认。',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '产品存在公开入口；收入、客户和融资均待独立验证。',
        competitors: '生成式视频、3D 工具、创意软件和视觉模型公司。',
        relatedEvents: ['metamorph-2026', 'world-summit-ai'],
        publicContacts: [{ label: '公司官网', url: 'https://lumalabs.ai/' }],
        sources: [source('Luma AI 官网', 'https://lumalabs.ai/', '官网')],
        discoveredAt: '2026-07-14 17:05',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '公开产品入口可用，其他重要公司信息待核验。',
        score: { novelty: 4, source: 3, completeness: 3, relevance: 4, stage: 3, followup: 3 },
        why: ['内容生产链条中，视频与 3D 生成有明显的工程和商业化分歧。', '可以跟踪模型能力到生产工具的转化。'],
        uncertainties: ['商业客户需求、产品付费模型和内容安全机制待验证。'],
        verifyQuestions: ['商业生产使用频率和替代方案？', '视频/3D 两条路线是否共享技术和销售渠道？']
      },
      {
        id: 'unstructured',
        name: 'Unstructured',
        industry: 'AI 基础设施',
        subSector: '非结构化数据处理',
        region: '北美',
        location: '待公开资料核验',
        description: '将文档、PDF、邮件等非结构化数据转化为可被 AI 系统使用的数据。',
        fullDescription: 'Unstructured 官网展示将企业非结构化数据摄取、分块和处理为 AI/RAG 工作流可用资产的能力。',
        product: '非结构化数据摄取、解析、转换和 RAG 数据处理平台。',
        targetCustomers: '需要把企业文档和知识资产用于 AI 应用的开发和数据团队。',
        aiApproach: '文档解析、数据标准化、检索准备与 AI 数据管线。',
        founders: 'Brian Raymond 等（待二次核验）',
        founderBackground: '待公司/权威公开资料确认。',
        stage: '未知',
        amount: '未知',
        valuation: '未知',
        lastFunding: '未知',
        bBefore: '待核验',
        commercial: '公开产品与文档入口可访问；具体客户、融资和商业指标待验证。',
        competitors: '数据连接器、文档解析、RAG 平台和企业搜索。',
        relatedEvents: ['agent-craft', 'world-summit-ai'],
        publicContacts: [{ label: '公司官网', url: 'https://www.unstructured.io/' }],
        sources: [source('Unstructured 官网', 'https://www.unstructured.io/', '官网')],
        discoveredAt: '2026-07-14 16:46',
        informationUpdatedAt: capturedAt,
        sourceUpdate: '本地样本写入时间：2026-07-15。',
        confidence: '中',
        confidenceNote: '产品方向有官网来源；团队、融资与客户需独立佐证。',
        score: { novelty: 3, source: 3, completeness: 3, relevance: 5, stage: 3, followup: 4 },
        why: ['数据质量通常决定企业 Agent 能否可靠落地。', '可与知识 Agent、权限与检索场景关联研究。'],
        uncertainties: ['解析质量、企业集成复杂度和竞争差异待验证。'],
        verifyQuestions: ['数据处理准确性如何评估？', '开源与商业产品的转化路径？', '是否能覆盖复杂表格、图像与权限？']
      }
    ],
    ingestionTestCases: {
      duplicates: [
        { rawCandidate: 'Spine AI / YC company profile', canonicalProjectId: 'spine-ai', resolution: '按相同公司主页与名称合并；不新增项目卡。' },
        { rawCandidate: 'Vapi / YC profile + official website', canonicalProjectId: 'vapi', resolution: '保留两个来源链接，合并为一个实体。' },
        { rawCandidate: 'Broccoli / YC profile + company website', canonicalProjectId: 'broccoli-ai', resolution: '按公开官网与公司名称合并；融资字段保持待核验。' }
      ],
      missingFields: ['tasklet', 'manus', 'genspark', 'cartesia', 'hamming-ai', 'rhizome-ai'],
      lowValueEvents: ['ai-house-kpmg', 'metamorph-2026', 'national-ai-awards']
    },
    events: [
      {
        id: 'world-ai-week-2026',
        name: 'World AI Week 2026',
        date: '2026-10-05 — 2026-10-09',
        isoStart: '2026-10-05',
        location: 'Amsterdam, Netherlands',
        mode: '线下 / 分布式活动周',
        organizer: 'World Summit AI',
        type: '活动周',
        theme: 'AI 商业、科学、技术与社群交流',
        speakers: ['以各子活动官网为准'],
        speakerQuality: '高（主办方定位为全球 AI 生态活动周；个别子活动需逐一核验）',
        audience: '创始人、研究人员、企业 AI 团队、投资人与开发者',
        investorValue: '可从主会与分会筛选创业者、模型与基础设施机会；需避免只参加泛社交场。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '官方页面说明有多场关联活动，覆盖商业、科技和社群；须在报名/行程阶段继续筛选具体子活动。',
        score: { topic: 5, speakers: 4, format: 5, investor: 5, discovery: 5, source: 5, urgency: 4 },
        sources: [source('World Summit AI 官方活动列表', 'https://worldsummit.ai/all-events/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['spine-ai', 'raindrop', 'mistral-ai', 'dust'],
        attendeesToWatch: ['早期 AI 创始团队', '模型 / Agent 基础设施从业者', '活动周分会主办方'],
        nextAction: '从官方活动周清单中按“创业展示、技术深度、可预约交流”筛选 3 场子活动。'
      },
      {
        id: 'world-summit-ai',
        name: 'World Summit AI 2026',
        date: '2026-10-07 — 2026-10-08',
        isoStart: '2026-10-07',
        location: 'Taets Art & Event Park, Amsterdam, Netherlands',
        mode: '线下',
        organizer: 'World Summit AI',
        type: '国际峰会',
        theme: '前沿 AI、部署、治理、创业与产业合作',
        speakers: ['官方 2026 speaker lineup（详见来源页）'],
        speakerQuality: '高（官方页面列示全球研究者、企业与创始人阵容；个别嘉宾以正式议程为准）',
        audience: '全球 AI 创始人、企业高管、研究者、开发者与投资人',
        investorValue: '适合做产业地图和跨区域创始人会面；应预先预约、按赛道组织行程。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '官方页明确面向创业者、投资人、研究者和企业，且有产品发布与高密度主题场。',
        score: { topic: 5, speakers: 5, format: 4, investor: 5, discovery: 5, source: 5, urgency: 4 },
        sources: [source('World Summit AI 官方主页', 'https://worldsummit.ai/', '官网'), source('World Summit AI 行程信息', 'https://worldsummit.ai/plan-your-trip/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['spine-ai', 'raindrop', 'vapi', 'mistral-ai', 'dust', 'baseten'],
        attendeesToWatch: ['模型公司业务负责人', 'Agent 基础设施创始人', '产业 AI 企业与技术投资人'],
        nextAction: '报名后以主题 track、创业展示和一对一预约为单位组织会面名单。'
      },
      {
        id: 'world-summit-ai-doha',
        name: 'World Summit AI Doha 2026',
        date: '2026-12-15 — 2026-12-16',
        isoStart: '2026-12-15',
        location: 'Doha, Qatar（具体场地以官方页为准）',
        mode: '线下',
        organizer: 'World Summit AI Global Summit Series',
        type: '国际峰会',
        theme: '全球 AI 生态、企业与政策交流',
        speakers: ['待官方完整议程更新'],
        speakerQuality: '中（官方列出日期和城市，完整 lineup 待确认）',
        audience: '区域企业、政策与 AI 生态参与者',
        investorValue: '可用于观察中东企业 AI 需求和区域项目；需要先确认创业展示与参会者结构。',
        discoveryPotential: '中',
        quality: '中',
        qualityReason: '活动系列有主办方来源，但详细议程、嘉宾与创业项目结构尚未完整收录。',
        score: { topic: 4, speakers: 3, format: 4, investor: 4, discovery: 3, source: 5, urgency: 3 },
        sources: [source('World Summit AI 官方活动列表', 'https://worldsummit.ai/all-events/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['mistral-ai', 'baseten'],
        attendeesToWatch: ['区域云与企业 AI 决策者', '中东 AI 创业项目'],
        nextAction: '等待官方议程后，判断是否有开放创业展示或垂直场。'
      },
      {
        id: 'neurips-2026',
        name: 'NeurIPS 2026',
        date: '2026-12-06 — 2026-12-12',
        isoStart: '2026-12-06',
        location: '具体城市待官网确认',
        mode: '线上 + 线下（以官网最终安排为准）',
        organizer: 'NeurIPS Foundation',
        type: '学术会议',
        theme: '机器学习与神经信息处理系统',
        speakers: ['主会、tutorial、workshop 讲者待正式议程'],
        speakerQuality: '高（顶级学术会议；具体日程需以官网为准）',
        audience: '研究者、模型公司、创业者、开发者与招聘团队',
        investorValue: '对模型、评测、AI safety 和研究型创业项目有较高信息价值；项目发现更依赖 workshops、satellite events 和会前约谈。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '官方日期页明确主会、tutorial 与 workshop 安排；研究密度高，但商业项目筛选需要额外机制。',
        score: { topic: 5, speakers: 5, format: 4, investor: 4, discovery: 4, source: 5, urgency: 4 },
        sources: [source('NeurIPS 2026 官方日期页', 'https://neurips.cc/Conferences/2026/Dates', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['raindrop', 'superagent', 'mistral-ai'],
        attendeesToWatch: ['paper authors', 'workshop organizers', '模型/评测研究团队'],
        nextAction: '在 paper acceptance 后按 Agent、eval、安全与垂直 AI 论文建立创始人/实验室名单。'
      },
      {
        id: 'gtc-2026',
        name: 'NVIDIA GTC 2026',
        date: '2026-03-16 — 2026-03-19（已结束，保留为历史样本）',
        isoStart: '2026-03-16',
        location: 'San Jose, California, US',
        mode: '线下 + 线上内容',
        organizer: 'NVIDIA',
        type: '产业技术大会',
        theme: 'AI、加速计算、机器人、开发者生态',
        speakers: ['Jensen Huang keynote；其余议程见官方来源'],
        speakerQuality: '高',
        audience: '模型公司、基础设施、开发者、企业、机器人与研究人员',
        investorValue: '适合识别算力、推理、工具链和 physical AI 的产业变化；规模大，需避免漫游式参会。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '官方页面说明其覆盖 AI、开发者、研究与商业参与者；技术与生态信息密度高。',
        score: { topic: 5, speakers: 5, format: 4, investor: 5, discovery: 4, source: 5, urgency: 1 },
        sources: [source('NVIDIA GTC 官方页', 'https://www.nvidia.com/gtc/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['baseten', 'spine-ai', 'luma-ai'],
        attendeesToWatch: ['推理基础设施团队', '机器人/physical AI 创业者', '云与芯片生态伙伴'],
        nextAction: '复盘官方 session 录像与生态伙伴名单，提炼下届会前跟踪赛道。'
      },
      {
        id: 'ai-summit-london',
        name: 'The AI Summit London 2026',
        date: '2026-06-10 — 2026-06-11（已结束，保留为历史样本）',
        isoStart: '2026-06-10',
        location: 'Tobacco Dock, London, UK',
        mode: '线下',
        organizer: 'The AI Summit / Informa',
        type: '企业 AI 峰会',
        theme: '企业 AI、行业应用、治理、MLOps 和商业落地',
        speakers: ['官方称 300+ senior leaders；完整阵容见官网'],
        speakerQuality: '高（官方页列有企业与政策领域代表）',
        audience: '企业 AI 负责人、创业者、投资人、服务商与开发者',
        investorValue: '适合研究企业采购、垂直应用和 Start-up & Investor Village；对早期项目发现有明确机制。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '官方议程含创业与投资村、pitch 与互动体验，且主题覆盖企业部署。',
        score: { topic: 5, speakers: 4, format: 5, investor: 5, discovery: 5, source: 5, urgency: 1 },
        sources: [source('The AI Summit London 官方议程', 'https://london.theaisummit.com/agenda-overview/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['decagon', 'dust', 'harvey', 'lovable', 'origami-agents'],
        attendeesToWatch: ['Start-up & Investor Village 入选团队', '企业 AI 负责人', '垂直 AI 创始人'],
        nextAction: '复盘 2026 创业展示名单，建立 2027 早期项目的回访和会前预约模板。'
      },
      {
        id: 'agent-craft',
        name: 'Agent Craft（AI Summit London Fringe）',
        date: '2026-06-12（已结束，保留为历史样本）',
        isoStart: '2026-06-12',
        location: 'Brainstation, London, UK',
        mode: '线下 / unconference',
        organizer: 'AI Summit London Fringe 关联活动',
        type: '开发者社群活动',
        theme: 'OpenClaw、n8n、Claude Code、LangChain、Agentic Automation、安全与可靠性',
        speakers: ['由参会者驱动议题；少量 keynote/demos'],
        speakerQuality: '中（议程由现场参与者共同驱动）',
        audience: 'Agent 构建者、开发者、自动化实践者',
        investorValue: '比大型主会更可能接触真实 builder；但需要事先判断与目标赛道的相关性。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '开放式小规模讨论和 demo 形式有利于发现早期 builder，且主题与 Agent 实践直接相关。',
        score: { topic: 5, speakers: 3, format: 5, investor: 4, discovery: 5, source: 5, urgency: 1 },
        sources: [source('AI Summit London Fringe 官方页', 'https://london.theaisummit.com/conference-agenda/fringe-events/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['spine-ai', 'tasklet', 'genspark', 'cursor', 'unstructured'],
        attendeesToWatch: ['独立 Agent builder', '开源工具贡献者', '自动化/Agent 早期创始人'],
        nextAction: '关注下一届是否开放报名；准备“正在研究哪些 Agent 工作流”的 30 秒交流问题。'
      },
      {
        id: 'ai-house-kpmg',
        name: 'AI House presented by KPMG（AI Summit London Fringe）',
        date: '2026-06-08 — 2026-06-14（已结束，保留为历史样本）',
        isoStart: '2026-06-08',
        location: 'London, UK（具体入场信息以主办方为准）',
        mode: '线下 / 邀请制',
        organizer: 'KPMG / AI Summit London Fringe',
        type: '品牌与高管交流活动',
        theme: '企业 AI 与高管交流',
        speakers: ['以邀请函与官方页面为准'],
        speakerQuality: '中',
        audience: '受邀企业高管与合作伙伴',
        investorValue: '可能触达企业决策者，但开放性低、项目发现机制不清晰。',
        discoveryPotential: '低',
        quality: '低',
        qualityReason: '邀请制高管品牌活动，公开信息未显示创业展示或结构化项目发现机制；适合作为企业客户研究而非优先扫项目活动。',
        score: { topic: 3, speakers: 3, format: 2, investor: 3, discovery: 1, source: 4, urgency: 1 },
        sources: [source('AI Summit London Fringe 官方页', 'https://london.theaisummit.com/conference-agenda/fringe-events/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['decagon', 'harvey', 'dust'],
        attendeesToWatch: ['企业 AI 采购与实施负责人'],
        nextAction: '仅在有明确受邀、客户洞察目标或可约会对象时考虑参加。'
      },
      {
        id: 'metamorph-2026',
        name: 'MetaMorph 2026（AI 创意奖项活动）',
        date: '2026-06-09（已结束，保留为历史样本）',
        isoStart: '2026-06-09',
        location: 'Castle Cinema, London, UK',
        mode: '线下',
        organizer: 'AI Summit London Fringe 关联活动',
        type: '创意 AI 奖项活动',
        theme: 'AI 与影视、音乐、创意生产',
        speakers: ['官方页列出评审与创意产业人士；完整名单见来源'],
        speakerQuality: '中',
        audience: '创意从业者、内容制作者与品牌合作方',
        investorValue: '可观察创意 AI 的人才和案例，但以奖项/展示为主，早期项目信号较弱。',
        discoveryPotential: '低',
        quality: '低',
        qualityReason: '活动有创意行业价值，但主体为奖项庆典与展示，缺少明确的项目筛选或深度交流机制。',
        score: { topic: 3, speakers: 3, format: 2, investor: 2, discovery: 2, source: 4, urgency: 1 },
        sources: [source('AI Summit London Fringe 官方页', 'https://london.theaisummit.com/conference-agenda/fringe-events/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['pika', 'luma-ai'],
        attendeesToWatch: ['创意 AI 工具创始人', '生成式内容制作团队'],
        nextAction: '如研究创意 AI，可回看获奖项目与评审名单；不作为常规扫项目优先项。'
      },
      {
        id: 'national-ai-awards',
        name: 'The National AI Awards Ceremony 2026',
        date: '2026-06-10（已结束，保留为历史样本）',
        isoStart: '2026-06-10',
        location: 'London, UK',
        mode: '线下',
        organizer: 'The AI Summit London 关联活动',
        type: '颁奖典礼',
        theme: 'AI 行业奖项',
        speakers: ['获奖者与嘉宾以官方活动页为准'],
        speakerQuality: '未知 / 待具体名单核验',
        audience: '赞助商、获奖者、行业嘉宾',
        investorValue: '品牌与行业名片价值高于早期项目发现；若无明确会面目标，优先级低。',
        discoveryPotential: '低',
        quality: '低',
        qualityReason: '颁奖典礼通常是宣传与品牌场景，官方议程没有显示结构化的项目发现或深度讨论机制。',
        score: { topic: 2, speakers: 2, format: 1, investor: 2, discovery: 1, source: 4, urgency: 1 },
        sources: [source('The AI Summit London 官方议程', 'https://london.theaisummit.com/agenda-overview/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: [],
        attendeesToWatch: ['若已知获奖创业团队，可定向联系'],
        nextAction: '仅在已有特定获奖团队研究目标时保留；否则忽略。'
      },
      {
        id: 'superai-2026',
        name: 'SuperAI 2026',
        date: '2026-06-10 — 2026-06-11（已结束，保留为历史样本）',
        isoStart: '2026-06-10',
        location: 'Singapore（具体会场以官网为准）',
        mode: '线下',
        organizer: 'SuperAI',
        type: '国际 AI 峰会',
        theme: '全球 AI、创业、企业与技术生态',
        speakers: ['官方报告/官网列示，具体阵容以活动页为准'],
        speakerQuality: '高',
        audience: '亚洲与全球创始人、投资人、企业和技术从业者',
        investorValue: '适合观察东南亚和全球 AI 创业生态；参会前需要按 showcase、主题场和约会对象筛选。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '官方活动资料将其定位为大型 AI 生态聚会，具备创始人与投资人交流价值。',
        score: { topic: 5, speakers: 4, format: 4, investor: 5, discovery: 5, source: 4, urgency: 1 },
        sources: [source('SuperAI 官方页面', 'https://www.superai.com/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['vapi', 'hamming-ai', 'cartesia'],
        attendeesToWatch: ['东南亚 AI 创始团队', 'Voice AI 与 Agent 开发者', '区域企业 AI 决策者'],
        nextAction: '回看 2026 展商/演讲者名单，筛选亚洲 AI 项目并为下一届建立约会清单。'
      },
      {
        id: 'ai-for-good-2026',
        name: 'AI for Good Global Summit 2026',
        date: '2026 年度活动（具体日期与场地待官方当前页核验）',
        isoStart: '2026-09-01',
        location: 'Geneva, Switzerland（待官方当前页核验）',
        mode: '线下 + 线上（待确认）',
        organizer: 'International Telecommunication Union（ITU）',
        type: '国际公共议题峰会',
        theme: 'AI 治理、社会影响、医疗、可持续发展',
        speakers: ['待官方完整议程'],
        speakerQuality: '高（国际组织平台；具体嘉宾待确认）',
        audience: '国际组织、研究者、政策制定者、企业与社会创新团队',
        investorValue: '适合发现公共议题、医疗与可信 AI 的合作线索；不一定是高密度早期项目场。',
        discoveryPotential: '中',
        quality: '中',
        qualityReason: '议题和机构价值高，但创业项目密度、交流形式和具体日期需进一步核验。',
        score: { topic: 5, speakers: 4, format: 3, investor: 3, discovery: 3, source: 4, urgency: 3 },
        sources: [source('AI for Good 官方主页', 'https://aiforgood.itu.int/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['abridge', 'rhizome-ai', 'superagent'],
        attendeesToWatch: ['医疗 AI 团队', '可信 AI 研究者', '公共部门创新组织'],
        nextAction: '先核验 2026 日期和创业展示机制，再决定是否纳入出行计划。'
      },
      {
        id: 'iclr-2026',
        name: 'ICLR 2026',
        date: '2026 年度会议（已结束；具体会期应以官方归档为准）',
        isoStart: '2026-04-23',
        location: '待官网归档核验',
        mode: '会议形式以官方归档为准',
        organizer: 'ICLR',
        type: '学术会议',
        theme: '深度学习与表示学习',
        speakers: ['主会 / workshop 资料见官方档案'],
        speakerQuality: '高',
        audience: '机器学习研究者、模型团队、研究型创业者',
        investorValue: '适合捕捉研究前沿、实验室人才和模型方向；与早期项目接触需要配合 workshop 和社群。',
        discoveryPotential: '中',
        quality: '高',
        qualityReason: '顶级研究会议，学术信息质量高；商业项目发现能力取决于会外组织。',
        score: { topic: 5, speakers: 5, format: 3, investor: 3, discovery: 3, source: 5, urgency: 1 },
        sources: [source('ICLR 2026 官方会议页', 'https://iclr.cc/Conferences/2026', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['mistral-ai', 'raindrop', 'spine-ai'],
        attendeesToWatch: ['论文作者', 'workshop 主办者', '高校实验室 spinout'],
        nextAction: '从接受论文和 workshop 中筛选可能的项目化方向。'
      },
      {
        id: 'icml-2026',
        name: 'ICML 2026',
        date: '2026 年度会议（具体会期与场地待官方页核验）',
        isoStart: '2026-07-20',
        location: '待官方当前页核验',
        mode: '待官方确认',
        organizer: 'International Conference on Machine Learning',
        type: '学术会议',
        theme: '机器学习研究与应用',
        speakers: ['论文、tutorial、workshop 讲者待官方页确认'],
        speakerQuality: '高',
        audience: 'AI 研究者、模型团队、学生、企业研究部门',
        investorValue: '有助于研究模型、评测和技术人才；项目发现须通过 workshop、side event 和团队约谈完成。',
        discoveryPotential: '中',
        quality: '高',
        qualityReason: '长期高影响力机器学习会议；此 Demo 未将未经确认的 2026 场地/日期填入数据。',
        score: { topic: 5, speakers: 5, format: 3, investor: 3, discovery: 3, source: 4, urgency: 4 },
        sources: [source('ICML 官方会议入口', 'https://icml.cc/Conferences/2026', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['mistral-ai', 'baseten', 'unstructured'],
        attendeesToWatch: ['研究型创业者', '模型系统作者', '开源项目维护者'],
        nextAction: '先打开官方页核验时间地点与 workshop 名单，再做会前筛选。'
      },
      {
        id: 'cvpr-2026',
        name: 'CVPR 2026',
        date: '2026 年度会议（已结束；具体会期以官方归档为准）',
        isoStart: '2026-06-03',
        location: '待官方归档核验',
        mode: '待官方归档确认',
        organizer: 'Computer Vision Foundation',
        type: '学术会议',
        theme: '计算机视觉、生成式视觉、机器人感知',
        speakers: ['主会 / workshop 讲者见官方档案'],
        speakerQuality: '高',
        audience: '视觉研究者、生成式内容、机器人和视觉 AI 创业者',
        investorValue: '对视觉模型、生成式视频、机器人感知项目有价值；项目发现更适合在 workshop/赞助方生态中进行。',
        discoveryPotential: '中',
        quality: '高',
        qualityReason: '计算机视觉顶级会议信息密度高；商业项目沟通需要额外安排。',
        score: { topic: 5, speakers: 5, format: 3, investor: 3, discovery: 3, source: 4, urgency: 1 },
        sources: [source('CVPR 2026 官方会议页', 'https://cvpr.thecvf.com/Conferences/2026', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['pika', 'luma-ai'],
        attendeesToWatch: ['生成式视觉论文作者', '机器人视觉团队', '3D/视频模型创业者'],
        nextAction: '根据 paper 与 workshop 主题建立生成式视觉和 physical AI 跟踪表。'
      },
      {
        id: 'aaai-2026',
        name: 'AAAI-26',
        date: '2026 年度会议（已结束；具体会期以官方归档为准）',
        isoStart: '2026-01-20',
        location: 'Singapore Expo（待官方归档核验）',
        mode: '待官方归档确认',
        organizer: 'AAAI',
        type: '学术会议',
        theme: '人工智能研究、应用与社会影响',
        speakers: ['以官方归档为准'],
        speakerQuality: '高',
        audience: 'AI 研究者、学生、创业者与行业团队',
        investorValue: '可用于亚洲研究生态和研究型创业者发现；需避免把学术曝光等同于商业准备度。',
        discoveryPotential: '中',
        quality: '高',
        qualityReason: '研究议题与国际参与者价值较高；此记录对日期/场地保持“待归档核验”。',
        score: { topic: 5, speakers: 5, format: 3, investor: 3, discovery: 3, source: 4, urgency: 1 },
        sources: [source('AAAI-26 官方页', 'https://aaai.org/conference/aaai/aaai-26/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['rhizome-ai', 'superagent'],
        attendeesToWatch: ['研究型学生创业者', '区域高校实验室', '应用型 AI 团队'],
        nextAction: '从 accepted papers 和 workshop 组织者中识别可追踪团队。'
      },
      {
        id: 'vivatech-2026',
        name: 'Viva Technology 2026',
        date: '2026-06-17 — 2026-06-20（已结束；需以官方页复核）',
        isoStart: '2026-06-17',
        location: 'Paris, France',
        mode: '线下',
        organizer: 'Viva Technology',
        type: '科技与创业大会',
        theme: '科技创业、企业创新与 AI',
        speakers: ['官方日程和展商目录为准'],
        speakerQuality: '中',
        audience: '欧洲创始人、企业创新团队、投资人和媒体',
        investorValue: '创业展示和企业合作机会较多，但泛科技范围大，需要把 AI 项目筛选前置。',
        discoveryPotential: '中',
        quality: '中',
        qualityReason: '创业生态与规模有价值，但 AI 不是唯一主题，需按展区和赛道筛选。',
        score: { topic: 3, speakers: 3, format: 4, investor: 4, discovery: 4, source: 3, urgency: 1 },
        sources: [source('Viva Technology 官方主页', 'https://vivatechnology.com/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['mistral-ai', 'dust', 'lovable'],
        attendeesToWatch: ['欧洲 AI 创始人', '企业创新负责人', '创业展区入选项目'],
        nextAction: '从官方 startup 目录中提取 AI 子集，剔除泛数字化展商。'
      },
      {
        id: 'data-ai-summit-2026',
        name: 'Databricks Data + AI Summit 2026',
        date: '2026-06-15 — 2026-06-18（已结束；需以官方页复核）',
        isoStart: '2026-06-15',
        location: 'San Francisco, US（待官方归档核验）',
        mode: '线下 + 线上内容',
        organizer: 'Databricks',
        type: '数据与 AI 产业大会',
        theme: '数据、AI、企业平台与开发者生态',
        speakers: ['以官方议程为准'],
        speakerQuality: '高（企业数据/AI 技术生态）',
        audience: '数据平台、AI 工程团队、企业客户和开发者',
        investorValue: '适合发现数据与企业 AI 基础设施机会；项目发现依赖生态伙伴与开发者活动。',
        discoveryPotential: '中',
        quality: '高',
        qualityReason: '与企业数据和 AI 部署强相关；但更偏平台生态，需要有明确的关注清单。',
        score: { topic: 5, speakers: 4, format: 4, investor: 4, discovery: 3, source: 3, urgency: 1 },
        sources: [source('Databricks Data + AI Summit 官方页', 'https://www.databricks.com/data-and-ai-summit', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['unstructured', 'baseten', 'raindrop'],
        attendeesToWatch: ['企业 RAG / data infra 创始人', '生态合作伙伴', '数据平台购买者'],
        nextAction: '复盘 sponsor 与 ecosystem 名单，筛选 AI data layer 初创公司。'
      },
      {
        id: 'computex-2026',
        name: 'COMPUTEX 2026 / GTC Taipei',
        date: '2026-06-01 — 2026-06-05（已结束；需以官方页复核）',
        isoStart: '2026-06-01',
        location: 'Taipei, Taiwan',
        mode: '线下',
        organizer: 'COMPUTEX / NVIDIA 关联活动',
        type: '计算与硬件产业大会',
        theme: 'AI 硬件、边缘计算、芯片与开发者生态',
        speakers: ['官方 keynote 与参展商资料为准'],
        speakerQuality: '高',
        audience: '芯片、硬件、OEM、AI 基础设施、开发者与媒体',
        investorValue: '对 AI 硬件、端侧、算力供应链有价值；软件项目发现不是主目标。',
        discoveryPotential: '中',
        quality: '高',
        qualityReason: '产业链和技术展示密集，适合硬件/基础设施投资人；需明确项目筛选规则。',
        score: { topic: 5, speakers: 4, format: 4, investor: 4, discovery: 3, source: 3, urgency: 1 },
        sources: [source('COMPUTEX 官方主页', 'https://www.computextaipei.com.tw/', '官网'), source('NVIDIA GTC 官方页', 'https://www.nvidia.com/gtc/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['baseten', 'luma-ai'],
        attendeesToWatch: ['AI 终端和模组团队', '推理硬件生态', '开发者工具合作伙伴'],
        nextAction: '按“端侧 AI、机器人、推理算力”准备供应链与创业项目扫描问题。'
      },
      {
        id: 'waic-2025',
        name: 'World Artificial Intelligence Conference 2025',
        date: '2025 年度活动（历史样本；具体会期需官方归档核验）',
        isoStart: '2025-07-26',
        location: 'Shanghai, China（待官方归档核验）',
        mode: '线下',
        organizer: 'World Artificial Intelligence Conference',
        type: 'AI 产业大会',
        theme: 'AI 产业、模型、机器人与全球治理',
        speakers: ['以官方归档和 2026 预告为准'],
        speakerQuality: '高',
        audience: '中国及全球 AI 企业、研究机构、政策和投资生态',
        investorValue: '对中国 AI 项目、产业链和政策变化有高价值；需提前按创业公司和分论坛筛选。',
        discoveryPotential: '高',
        quality: '高',
        qualityReason: '大型 AI 产业会议，主题覆盖面广；建议用具体论坛和项目展示做二次筛选。',
        score: { topic: 5, speakers: 4, format: 4, investor: 5, discovery: 5, source: 3, urgency: 1 },
        sources: [source('WAIC 官方主页', 'https://www.worldaic.com.cn/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['manus', 'genspark'],
        attendeesToWatch: ['中国模型与 Agent 创业团队', '具身与端侧 AI 团队', '产业客户'],
        nextAction: '等待 2026 官方议程，优先挑选项目展示、闭门交流与产业主题论坛。'
      },
      {
        id: 'rise-of-ai-2026',
        name: 'Rise of AI Summit 2026',
        date: '2026 年度活动（具体日期、地点待官方页核验）',
        isoStart: '2026-09-15',
        location: 'Berlin, Germany（待官方页核验）',
        mode: '待官方确认',
        organizer: 'Rise of AI',
        type: 'AI 商业峰会',
        theme: 'AI 商业、创业、投资与欧洲生态',
        speakers: ['待官方议程'],
        speakerQuality: '中',
        audience: '欧洲创业者、企业和投资人',
        investorValue: '可作为欧洲 AI 生态补充来源；在未确认议程和创业机制前仅中等优先级。',
        discoveryPotential: '中',
        quality: '中',
        qualityReason: '活动主题匹配，但本样本未抓取到可验证的 2026 详细议程。',
        score: { topic: 4, speakers: 3, format: 3, investor: 4, discovery: 3, source: 3, urgency: 3 },
        sources: [source('Rise of AI 官方主页', 'https://www.riseof.ai/', '官网')],
        informationUpdatedAt: capturedAt,
        relatedProjects: ['lovable', 'mistral-ai', 'dust'],
        attendeesToWatch: ['欧洲企业 AI 创始人', '区域投资人', '应用型 AI 团队'],
        nextAction: '核验 2026 日期、讲者和 startup showcase 后再决定优先级。'
      }
    ]
  };
})();
