/* Generated by scripts/refresh-live-signals.mjs. Do not hand-edit. */
(function () {
  window.RADAR_LIVE_SIGNALS = {
  "version": 2,
  "generatedAt": "2026-07-17T19:34:51.788Z",
  "status": "success",
  "disclaimer": "实时队列以国内公开来源为优先，只收录待核验候选。未知字段保持未知；必须打开原始来源并由投资经理核验后，才能进入正式项目 / 活动信息池。",
  "sources": [
    {
      "id": "infoq-rss",
      "name": "InfoQ 中文（国内 AI / 创业 / 产品新闻）",
      "url": "https://www.infoq.cn/feed",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 0
    },
    {
      "id": "qbitai-rss",
      "name": "量子位 RSS（国内 AI 新闻）",
      "url": "https://www.qbitai.com/feed",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 2
    },
    {
      "id": "36kr-financing-flash",
      "name": "36氪融资快报（公开融资 / 创业线索）",
      "url": "https://pitchhub.36kr.com/financing-flash",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 10
    },
    {
      "id": "huodongxing-beijing",
      "name": "活动行：北京 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 2
    },
    {
      "id": "huodongxing-shanghai",
      "name": "活动行：上海 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 4
    },
    {
      "id": "huodongxing-shenzhen",
      "name": "活动行：深圳 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 3
    },
    {
      "id": "huodongxing-hangzhou",
      "name": "活动行：杭州 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 3
    },
    {
      "id": "huodongxing-guangzhou",
      "name": "活动行：广州 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%B9%BF%E5%B7%9E&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 2
    },
    {
      "id": "huodongxing-chengdu",
      "name": "活动行：成都 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E6%88%90%E9%83%BD&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-17T19:34:51.788Z",
      "records": 2
    }
  ],
  "projectCandidates": [
    {
      "id": "live-project-pjgnw8",
      "kind": "project",
      "name": "给AI发工号、定岗位、做绩效，数字员工终于能落地了",
      "category": "国内创业 / 产品待核验",
      "sourceName": "量子位 RSS（国内 AI 新闻）",
      "sourceUrl": "https://www.qbitai.com/feed",
      "url": "https://www.qbitai.com/2026/07/453245.html",
      "publishedAt": "2026-07-17T16:40:47.000Z",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "面壁智能开源StaffDeck",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "量子位 RSS（国内 AI 新闻）",
          "url": "https://www.qbitai.com/2026/07/453245.html",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 4,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-1ybttzr",
      "kind": "project",
      "name": "上海制造，AI入魂：央国企率先“重用”大模型，自动化设备被换下",
      "category": "国内创业 / 产品待核验",
      "sourceName": "量子位 RSS（国内 AI 新闻）",
      "sourceUrl": "https://www.qbitai.com/feed",
      "url": "https://www.qbitai.com/2026/07/453084.html",
      "publishedAt": "2026-07-17T10:17:23.000Z",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "来源未提供可用摘要；请打开原始链接核验主体、融资与产品信息。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "量子位 RSS（国内 AI 新闻）",
          "url": "https://www.qbitai.com/2026/07/453084.html",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 4,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-1n9riil",
      "kind": "project",
      "name": "前蔚来、华为智驾核心成员联手创业具身世界模型，三个月内完成数亿元融资",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3899081603483525",
      "publishedAt": "17小时前",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "在JEPA理论体系基础上进一步延伸。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3899081603483525",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-1leg5mj",
      "kind": "project",
      "name": "这家人形机器人ODM厂商获千万融资，飞荣达、索辰科技接连下注",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3899057634363266",
      "publishedAt": "18小时前",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "“自由执行任务”能力是未来行业竞争关键",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3899057634363266",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-81swvr",
      "kind": "project",
      "name": "商汤001号员工创办AI公司：将AI角色引擎做成护城河，获种子轮融资 | 36氪首发",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3898370289846153",
      "publishedAt": "19小时前",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "种子轮",
      "earlyStage": true,
      "summary": "角色不是静态prompt，而是一个会持续生长的数字生命。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：种子轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3898370289846153",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-12yu7fc",
      "kind": "project",
      "name": "斯年智驾获3亿元C轮融资，自动驾驶重卡赛道再升温｜36氪独家",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3895721094842249",
      "publishedAt": "2026-07-16",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "从非车规到车规，从测试走向规模化",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3895721094842249",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-pl8e97",
      "kind": "project",
      "name": "“问天量子”完成B轮融资",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3896750928775041",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "B轮",
      "earlyStage": false,
      "summary": "36氪获悉，近日，“问天量子”完成B轮融资，获得6亿元资金注入，新进投资方包括海南晴澜、海南量启、淄博汇富齐嘉等多家机构。此次融资资金将主要用于核心技术的规模化商用、量子随机数芯片的量产扩能，以及面向人工智能时代的量子AI融合产品研发。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：B轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3896750928775041",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-rh97j9",
      "kind": "project",
      "name": "“面壁智能”完成新一轮融资，估值超200亿元",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3896612236265095",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "36氪获悉，面壁智能已完成新一轮融资，投资方包括国家级基金、央企、汽车制造商等各类产业方、财务投资人等。至此，面壁智能2026上半年累计融资金额超50亿元，估值超200亿元，一跃成为端侧智能领域公开估值最大的独角兽企业。面壁智能专注于将原生端侧大模型技术转化为标准化产品，在具身、汽车、手机、低空、民航等核心赛道落地，未来还将拓展至工业、家居、特种领域等。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3896612236265095",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-e4sd1j",
      "kind": "project",
      "name": "“灵巧智能”完成数亿元A轮融资，上海电气战略入股",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3896356363814530",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "天使轮",
      "earlyStage": true,
      "summary": "近日，具身智能企业“灵巧智能”（DexRobot）宣布完成数亿元A轮融资，本轮由上海电气战略投资，产业资本与财务资本持续加码。2026年内，公司已先后完成天使轮及A轮两轮融资，融资资金将重点用于灵巧操作全栈技术研发、核心产品迭代、教育/电力/工业三大场景落地及产业生态建设。此外，上海电气旗下上海机电与灵巧智能同步成立两家合资公司——灵机壹动与灵机智联，总注册资本超亿元，分别聚焦核心零部件量产与工业场景解决方案，标志着公司从技术研发迈入产业规模化交付阶段。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词、标题 / 摘要阶段线索：天使轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3896356363814530",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-15t0apj",
      "kind": "project",
      "name": "前非夕科技核心业务合伙人创业，做垂域工业智能体，获数千万元种子轮融资",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3896298534520705",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "种子轮",
      "earlyStage": true,
      "summary": "产品已落地首单交付。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：种子轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3896298534520705",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-fdw4ax",
      "kind": "project",
      "name": "“新奇机器人”完成A+轮融资",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3894938156465413",
      "publishedAt": "2026-07-14",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "A+轮",
      "earlyStage": true,
      "summary": "36氪获悉，近日，“新奇机器人”宣布完成A+轮融资。这是新奇机器人自2025年底启动首轮市场化融资以来，半年内完成的第三轮融资。本轮融资完成后，新奇机器人的投资人阵容涵盖经纬创投、沃赋创投、云晖资本、厚雪资本、Synstellation Capital等市场化投资机构，智元机器人、福然德等产业投资方，以及建发新兴投资、吴中金控、雉荟投资、宁波天使等国有背景资本。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词、标题 / 摘要阶段线索：A+轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3894938156465413",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    },
    {
      "id": "live-project-ew02fl",
      "kind": "project",
      "name": "「幻码跃迁」完成数千万元种子轮融资，打造量子 × AI 融合创新的量子计算基础设施",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3894898001181572",
      "publishedAt": "2026-07-14",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "stageHint": "种子轮",
      "earlyStage": true,
      "summary": "推动量子计算能力从实验环境走向真实场景，成为未来产业研发体系的新型计算基础设施。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：种子轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3894898001181572",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      }
    }
  ],
  "eventCandidates": [
    {
      "id": "live-event-18unq51",
      "kind": "event",
      "name": "AI直播与AI生成短视频交流沙龙第八期",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：北京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/4869976537900",
      "publishedAt": "07/23 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 北京 AI 公开目录收录。主办方：AI前沿学院；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 14:00（活动行列表页，年份待核验）",
        "location": "北京西城",
        "mode": "线下 / 待核验",
        "organizer": "AI前沿学院"
      },
      "sources": [
        {
          "title": "活动行：北京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/4869976537900",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-1nopt6k",
      "kind": "event",
      "name": "中关村创坛 | AI影视超创时代",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：北京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/2869032183411",
      "publishedAt": "今天 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 北京 AI 公开目录收录。主办方：车库咖啡；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "今天 14:00（活动行列表页，年份待核验）",
        "location": "北京海淀",
        "mode": "线下 / 待核验",
        "organizer": "车库咖啡"
      },
      "sources": [
        {
          "title": "活动行：北京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2869032183411",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-rofnbv",
      "kind": "event",
      "name": "AI产业出海峰会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/2865826950400",
      "publishedAt": "07/30 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：扬帆出海；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/30 周四 14:00（活动行列表页，年份待核验）",
        "location": "上海浦东",
        "mode": "线下 / 待核验",
        "organizer": "扬帆出海"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2865826950400",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-122c451",
      "kind": "event",
      "name": "企业级AI项目沟通会：世界人工智能大会可落地的AI项目【上海】",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/1869961296600",
      "publishedAt": "07/21 周二 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：司马阅；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/21 周二 14:00（活动行列表页，年份待核验）",
        "location": "上海黄浦",
        "mode": "线下 / 待核验",
        "organizer": "司马阅"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/1869961296600",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-1x2td9x",
      "kind": "event",
      "name": "2026上海具身智能机器人产业大会暨展览会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/3864492163100",
      "publishedAt": "08/12 周三 ~ 08/14 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：ExpoPro；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/12 周三 ~ 08/14 周五（活动行列表页，年份待核验）",
        "location": "上海浦东",
        "mode": "线下 / 待核验",
        "organizer": "ExpoPro"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/3864492163100",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-14p6vw6",
      "kind": "event",
      "name": "AGIC2026深圳人工智能展",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/5859922218300",
      "publishedAt": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：世界人工智能与物联网创新联盟（WAIA）；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "世界人工智能与物联网创新联盟（WAIA）"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/5859922218300",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-1n94sdu",
      "kind": "event",
      "name": "2026深圳物联网展-人工智能|机器人|AI|芯片|大模型|智能制造|通信定位|智慧商显|RFID等",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/9868330830000",
      "publishedAt": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：探世展览；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "探世展览"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9868330830000",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-10c97j1",
      "kind": "event",
      "name": "2026 AI赋能跨境电商与海外达人合作展览会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/7862775396900",
      "publishedAt": "08/04 周二 ~ 08/05 周三（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：TikTok 卖家门户网TKFFF；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/04 周二 ~ 08/05 周三（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "TikTok 卖家门户网TKFFF"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/7862775396900",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-1f9cbub",
      "kind": "event",
      "name": "【AI实战派】网易智企2026企业AI Agent规模化落地峰会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：杭州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/2868441463100",
      "publishedAt": "07/30 周四 13:30（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 杭州 AI 公开目录收录。主办方：网易智企；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/30 周四 13:30（活动行列表页，年份待核验）",
        "location": "浙江杭州",
        "mode": "线下 / 待核验",
        "organizer": "网易智企"
      },
      "sources": [
        {
          "title": "活动行：杭州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2868441463100",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-7neimv",
      "kind": "event",
      "name": "企业级AI项目合作沟通会：参展世界人工智能大会AI项目【杭州】",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：杭州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/8869547685300",
      "publishedAt": "07/23 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 杭州 AI 公开目录收录。主办方：司马阅；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 14:00（活动行列表页，年份待核验）",
        "location": "浙江杭州",
        "mode": "线下 / 待核验",
        "organizer": "司马阅"
      },
      "sources": [
        {
          "title": "活动行：杭州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/8869547685300",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-qnkg8q",
      "kind": "event",
      "name": "7月23日 阿里AI外贸跨境峰会（官方）",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：杭州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/2869740218100",
      "publishedAt": "07/23 周四 13:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 杭州 AI 公开目录收录。主办方：阿里国际站杭州总部；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 13:00（活动行列表页，年份待核验）",
        "location": "浙江杭州",
        "mode": "线下 / 待核验",
        "organizer": "阿里国际站杭州总部"
      },
      "sources": [
        {
          "title": "活动行：杭州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2869740218100",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-1kjzb81",
      "kind": "event",
      "name": "2026中国具身智能机器人产业大会暨展览会（大湾区）",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：广州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%B9%BF%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/8862866993800",
      "publishedAt": "10/21 周三 ~ 10/23 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 广州 AI 公开目录收录。主办方：探世展览；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "10/21 周三 ~ 10/23 周五（活动行列表页，年份待核验）",
        "location": "广东广州",
        "mode": "线下 / 待核验",
        "organizer": "探世展览"
      },
      "sources": [
        {
          "title": "活动行：广州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/8862866993800",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-1x5tpx2",
      "kind": "event",
      "name": "2026大湾区具身智能机器人产业大会暨展览会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：广州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%B9%BF%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/9862767310100",
      "publishedAt": "10/21 周三 ~ 10/23 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 广州 AI 公开目录收录。主办方：ExpoPro；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "10/21 周三 ~ 10/23 周五（活动行列表页，年份待核验）",
        "location": "广东广州",
        "mode": "线下 / 待核验",
        "organizer": "ExpoPro"
      },
      "sources": [
        {
          "title": "活动行：广州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9862767310100",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-fyaivs",
      "kind": "event",
      "name": "企业级AI项目沟通会：抢先布局AI商业化【成都】",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：成都 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%88%90%E9%83%BD&tag=AI",
      "url": "https://www.huodongxing.com/event/9865680203300",
      "publishedAt": "07/23 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 成都 AI 公开目录收录。主办方：司马阅；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 14:00（活动行列表页，年份待核验）",
        "location": "四川成都",
        "mode": "线下 / 待核验",
        "organizer": "司马阅"
      },
      "sources": [
        {
          "title": "活动行：成都 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9865680203300",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    },
    {
      "id": "live-event-1opz2ez",
      "kind": "event",
      "name": "四川外贸出海第一课｜成都工厂创业者AI跨境实战分享会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：成都 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%88%90%E9%83%BD&tag=AI",
      "url": "https://www.huodongxing.com/event/9869674477200",
      "publishedAt": "07/22 周三 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T19:34:51.788Z",
      "summary": "活动行 成都 AI 公开目录收录。主办方：外贸牛牛；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/22 周三 14:00（活动行列表页，年份待核验）",
        "location": "四川成都",
        "mode": "线下 / 待核验",
        "organizer": "外贸牛牛"
      },
      "sources": [
        {
          "title": "活动行：成都 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9869674477200",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      }
    }
  ]
};
})();
