/* Generated by scripts/refresh-live-signals.mjs. Do not hand-edit. */
(function () {
  window.RADAR_LIVE_SIGNALS = {
  "version": 3,
  "generatedAt": "2026-07-18T05:39:05.705Z",
  "status": "success",
  "disclaimer": "实时队列以国内公开来源为优先，保留近 45 天待核验候选。未知字段保持未知；必须打开原始来源并由投资经理核验后，才能进入正式项目 / 活动信息池。",
  "refreshCadence": "每 4 小时自动采集并发布一次（GitHub Actions 尽力调度）",
  "retention": {
    "days": 45,
    "maxProjectCandidates": 120,
    "maxEventCandidates": 120
  },
  "fresh": {
    "projects": 0,
    "events": 0
  },
  "sources": [
    {
      "id": "infoq-rss",
      "name": "InfoQ 中文（国内 AI / 创业 / 产品新闻）",
      "url": "https://www.infoq.cn/feed",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 0
    },
    {
      "id": "qbitai-rss",
      "name": "量子位 RSS（国内 AI 新闻）",
      "url": "https://www.qbitai.com/feed",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    },
    {
      "id": "36kr-financing-flash",
      "name": "36氪融资快报（公开融资 / 创业线索）",
      "url": "https://pitchhub.36kr.com/financing-flash",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 10
    },
    {
      "id": "36kr-rss-main",
      "name": "36氪 RSS（公开创投 / 科技资讯）",
      "url": "https://36kr.com/feed",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    },
    {
      "id": "36kr-rss-article",
      "name": "36氪文章 RSS（公开科技 / 创业报道）",
      "url": "https://36kr.com/feed-article",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 3
    },
    {
      "id": "36kr-rss-newsflash",
      "name": "36氪快讯 RSS（公开产品 / 融资快讯）",
      "url": "https://36kr.com/feed-newsflash",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 0
    },
    {
      "id": "huodongxing-beijing",
      "name": "活动行：北京 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-shanghai",
      "name": "活动行：上海 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 3
    },
    {
      "id": "huodongxing-shenzhen",
      "name": "活动行：深圳 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-hangzhou",
      "name": "活动行：杭州 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 3
    },
    {
      "id": "huodongxing-guangzhou",
      "name": "活动行：广州 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%B9%BF%E5%B7%9E&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    },
    {
      "id": "huodongxing-chengdu",
      "name": "活动行：成都 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E6%88%90%E9%83%BD&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-nanjing",
      "name": "活动行：南京 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%8D%97%E4%BA%AC&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-wuhan",
      "name": "活动行：武汉 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E6%AD%A6%E6%B1%89&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-suzhou",
      "name": "活动行：苏州 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E8%8B%8F%E5%B7%9E&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    },
    {
      "id": "huodongxing-xian",
      "name": "活动行：西安 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E8%A5%BF%E5%AE%89&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-chongqing",
      "name": "活动行：重庆 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E9%87%8D%E5%BA%86&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    },
    {
      "id": "huodongxing-tianjin",
      "name": "活动行：天津 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%A4%A9%E6%B4%A5&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    },
    {
      "id": "huodongxing-changsha",
      "name": "活动行：长沙 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E9%95%BF%E6%B2%99&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-hefei",
      "name": "活动行：合肥 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%90%88%E8%82%A5&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    },
    {
      "id": "huodongxing-xiamen",
      "name": "活动行：厦门 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E5%8E%A6%E9%97%A8&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 2
    },
    {
      "id": "huodongxing-qingdao",
      "name": "活动行：青岛 AI 活动目录",
      "url": "https://www.huodongxing.com/events?city=%E9%9D%92%E5%B2%9B&tag=AI",
      "status": "success",
      "fetchedAt": "2026-07-18T05:39:05.705Z",
      "records": 1
    }
  ],
  "projectCandidates": [
    {
      "id": "live-project-pjgnw8",
      "kind": "project",
      "name": "给AI发工号、定岗位、做绩效，数字员工终于能落地了",
      "category": "国内创业 / 产品待核验",
      "sourceName": "量子位 RSS（国内 AI 新闻）",
      "sourceUrl": "https://www.qbitai.com/feed",
      "url": "https://www.qbitai.com/2026/07/453245.html",
      "publishedAt": "2026-07-17T16:40:47.000Z",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "面壁智能开源StaffDeck",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "量子位 RSS（国内 AI 新闻）",
          "url": "https://www.qbitai.com/2026/07/453245.html",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 4,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-1n9riil",
      "kind": "project",
      "name": "前蔚来、华为智驾核心成员联手创业具身世界模型，三个月内完成数亿元融资",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3899081603483525",
      "publishedAt": "昨天",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "在JEPA理论体系基础上进一步延伸。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3899081603483525",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-1leg5mj",
      "kind": "project",
      "name": "这家人形机器人ODM厂商获千万融资，飞荣达、索辰科技接连下注",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3899057634363266",
      "publishedAt": "昨天",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "“自由执行任务”能力是未来行业竞争关键",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3899057634363266",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-81swvr",
      "kind": "project",
      "name": "商汤001号员工创办AI公司：将AI角色引擎做成护城河，获种子轮融资 | 36氪首发",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3898370289846153",
      "publishedAt": "昨天",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "种子轮",
      "earlyStage": true,
      "summary": "角色不是静态prompt，而是一个会持续生长的数字生命。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：种子轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3898370289846153",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-12yu7fc",
      "kind": "project",
      "name": "斯年智驾获3亿元C轮融资，自动驾驶重卡赛道再升温｜36氪独家",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3895721094842249",
      "publishedAt": "2026-07-16",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "从非车规到车规，从测试走向规模化",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3895721094842249",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-pl8e97",
      "kind": "project",
      "name": "“问天量子”完成B轮融资",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3896750928775041",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "B轮",
      "earlyStage": false,
      "summary": "36氪获悉，近日，“问天量子”完成B轮融资，获得6亿元资金注入，新进投资方包括海南晴澜、海南量启、淄博汇富齐嘉等多家机构。此次融资资金将主要用于核心技术的规模化商用、量子随机数芯片的量产扩能，以及面向人工智能时代的量子AI融合产品研发。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：B轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3896750928775041",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-rh97j9",
      "kind": "project",
      "name": "“面壁智能”完成新一轮融资，估值超200亿元",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3896612236265095",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "36氪获悉，面壁智能已完成新一轮融资，投资方包括国家级基金、央企、汽车制造商等各类产业方、财务投资人等。至此，面壁智能2026上半年累计融资金额超50亿元，估值超200亿元，一跃成为端侧智能领域公开估值最大的独角兽企业。面壁智能专注于将原生端侧大模型技术转化为标准化产品，在具身、汽车、手机、低空、民航等核心赛道落地，未来还将拓展至工业、家居、特种领域等。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3896612236265095",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-e4sd1j",
      "kind": "project",
      "name": "“灵巧智能”完成数亿元A轮融资，上海电气战略入股",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3896356363814530",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "天使轮",
      "earlyStage": true,
      "summary": "近日，具身智能企业“灵巧智能”（DexRobot）宣布完成数亿元A轮融资，本轮由上海电气战略投资，产业资本与财务资本持续加码。2026年内，公司已先后完成天使轮及A轮两轮融资，融资资金将重点用于灵巧操作全栈技术研发、核心产品迭代、教育/电力/工业三大场景落地及产业生态建设。此外，上海电气旗下上海机电与灵巧智能同步成立两家合资公司——灵机壹动与灵机智联，总注册资本超亿元，分别聚焦核心零部件量产与工业场景解决方案，标志着公司从技术研发迈入产业规模化交付阶段。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词、标题 / 摘要阶段线索：天使轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3896356363814530",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-15t0apj",
      "kind": "project",
      "name": "前非夕科技核心业务合伙人创业，做垂域工业智能体，获数千万元种子轮融资",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3896298534520705",
      "publishedAt": "2026-07-15",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "种子轮",
      "earlyStage": true,
      "summary": "产品已落地首单交付。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：种子轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3896298534520705",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-fdw4ax",
      "kind": "project",
      "name": "“新奇机器人”完成A+轮融资",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/newsflashes/3894938156465413",
      "publishedAt": "2026-07-14",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "A+轮",
      "earlyStage": true,
      "summary": "36氪获悉，近日，“新奇机器人”宣布完成A+轮融资。这是新奇机器人自2025年底启动首轮市场化融资以来，半年内完成的第三轮融资。本轮融资完成后，新奇机器人的投资人阵容涵盖经纬创投、沃赋创投、云晖资本、厚雪资本、Synstellation Capital等市场化投资机构，智元机器人、福然德等产业投资方，以及建发新兴投资、吴中金控、雉荟投资、宁波天使等国有背景资本。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词、标题 / 摘要阶段线索：A+轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/newsflashes/3894938156465413",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-ew02fl",
      "kind": "project",
      "name": "「幻码跃迁」完成数千万元种子轮融资，打造量子 × AI 融合创新的量子计算基础设施",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪融资快报（公开融资 / 创业线索）",
      "sourceUrl": "https://pitchhub.36kr.com/financing-flash",
      "url": "https://36kr.com/p/3894898001181572",
      "publishedAt": "2026-07-14",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "种子轮",
      "earlyStage": true,
      "summary": "推动量子计算能力从实验环境走向真实场景，成为未来产业研发体系的新型计算基础设施。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、标题 / 摘要阶段线索：种子轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪融资快报（公开融资 / 创业线索）",
          "url": "https://36kr.com/p/3894898001181572",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-1mt6vv3",
      "kind": "project",
      "name": "36氪首发 | 港科大博士创业做机器人全身触觉系统，红杉、瓴智、智元共同押注",
      "category": "国内早期创业 / 产品待核验",
      "sourceName": "36氪 RSS（公开创投 / 科技资讯）",
      "sourceUrl": "https://36kr.com/feed",
      "url": "https://36kr.com/p/3899128277452681?f=rss",
      "publishedAt": "2026-07-17T02:39:17.000Z",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "天使轮",
      "earlyStage": true,
      "summary": "作者 | 乔钰杰 编辑 | 袁斯来 硬氪获悉，全身多模态融合触觉解决方案公司模感科技（MoSense）近日完成数千万元天使轮融资，投资方包括红杉中国、高瓴创投及智元机器人。本轮融资资金将主要用于加速研发、团队扩充、算力投入及量产测试体系建设。 模感科技成立于2026年5月，总部注册于上海，在深圳前海设有研发中心，聚焦机器人全身多模态触觉感知系统研发。公司正式成立仅一个月便获得头部美元基金及人形厂商的共同押注。 随着人形机器人逐步从展示场景走向工业制造、物流搬运及家庭服务等真实复杂人物场景，机器人对环境的全面泛化感…",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词、标题 / 摘要阶段线索：天使轮；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪 RSS（公开创投 / 科技资讯）",
          "url": "https://36kr.com/p/3899128277452681?f=rss",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-mzefh",
      "kind": "project",
      "name": "打败Fable 5！Kimi K3冲上第一，杨植麟导师很骄傲",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪文章 RSS（公开科技 / 创业报道）",
      "sourceUrl": "https://36kr.com/feed-article",
      "url": "https://36kr.com/p/3899876606985864?f=rss",
      "publishedAt": "2026-07-18T01:42:13.000Z",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "智东西7月17日报道，今日，Kimi正式发布其迄今能力最强、全球首个开源的 3万亿 参数级别模型Kimi K3。该模型参数量达到 2.8万亿 ，原生支持视觉理解，并拥有 100万token 上下文窗口。 Kimi K3一上线便成为大模型顶流，不少网友将其发布称作“中国的Fable 5时刻”。就连Kimi创始人兼CEO杨植麟的博士生导师、CMU机器学习泰斗Russ Salakhutdinov也发贴盛赞新版Kimi为开源社区带来重大突破。 云平台Vercel创始人、Next.js作者Guillermo Rauch公布…",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪文章 RSS（公开科技 / 创业报道）",
          "url": "https://36kr.com/p/3899876606985864?f=rss",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-m30fk6",
      "kind": "project",
      "name": "Kimi K3：马斯克 Impressed",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪文章 RSS（公开科技 / 创业报道）",
      "sourceUrl": "https://36kr.com/feed-article",
      "url": "https://36kr.com/p/3899601903322244?f=rss",
      "publishedAt": "2026-07-17T11:04:06.000Z",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "7月16日晚，月之暗面扔出了K3。2.8万亿参数，Frontend Code Arena 1679分，压过了Claude Fable 5的1631分。7月27日前，完整权重开源。 官方博客里有句话很少见：\"整体表现仍落后于最强的闭源模型Claude Fable 5和GPT-5.6 Sol，但在我们的整套评测中展现出前沿水平的能力，并稳定超过了其他所有模型。\" 这种坦诚在国产大模型发布里算一股清流。它不装全能，只告诉你：我在编程这个主战场上，已经坐到了最靠前的位置。 1679分，X上先炸了 消息放出来后，X上的时间…",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪文章 RSS（公开科技 / 创业报道）",
          "url": "https://36kr.com/p/3899601903322244?f=rss",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-1y8ggtn",
      "kind": "project",
      "name": "梁文锋“狙击”闫俊杰",
      "category": "国内创业 / 产品待核验",
      "sourceName": "36氪文章 RSS（公开科技 / 创业报道）",
      "sourceUrl": "https://36kr.com/feed-article",
      "url": "https://36kr.com/p/3899475392906880?f=rss",
      "publishedAt": "2026-07-17T09:43:40.000Z",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "DeepSeek也可能要上市了。 据彭博最新消息，DeepSeek已经启动IPO准备，最快可能在今年提交申请。消息尚未得到DeepSeek官方证实，但如果顺利推进，继智谱和MiniMax之后，中国头部大模型公司又将多一家走进公开市场。 三家公司的业务彼此交叉，但外界关注的侧重点有所不同。智谱在Coding、Agent和企业API上的动作更加密集，MiniMax更受关注的是多模态和消费产品，DeepSeek最鲜明的标签则是开源、低成本和激进定价。 DeepSeek一旦上市，公开市场将多一把衡量中国大模型公司的参照尺…",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "36氪文章 RSS（公开科技 / 创业报道）",
          "url": "https://36kr.com/p/3899475392906880?f=rss",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-project-1ybttzr",
      "kind": "project",
      "name": "上海制造，AI入魂：央国企率先“重用”大模型，自动化设备被换下",
      "category": "国内创业 / 产品待核验",
      "sourceName": "量子位 RSS（国内 AI 新闻）",
      "sourceUrl": "https://www.qbitai.com/feed",
      "url": "https://www.qbitai.com/2026/07/453084.html",
      "publishedAt": "2026-07-17T10:17:23.000Z",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "来源未提供可用摘要；请打开原始链接核验主体、融资与产品信息。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "量子位 RSS（国内 AI 新闻）",
          "url": "https://www.qbitai.com/2026/07/453084.html",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 4,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-project-86lwc5",
      "kind": "project",
      "name": "397B参数追平万亿模型，上海AI Lab发布科学智能体新基座 | WAIC 2026",
      "category": "国内创业 / 产品待核验",
      "sourceName": "量子位 RSS（国内 AI 新闻）",
      "sourceUrl": "https://www.qbitai.com/feed",
      "url": "https://www.qbitai.com/2026/07/452942.html",
      "publishedAt": "2026-07-17T09:20:14.000Z",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "stageHint": "阶段待核验",
      "earlyStage": false,
      "summary": "采用非Transformer架构“Mobius”，不做泛化通用问答",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、创业 / 融资 / 产品关键词、国内主体 / 场景关键词；自动收录为国内优先候选，不代表已确认公司、融资、所在地或投资价值。",
      "unknowns": [
        "公司主体与国内经营主体：待核验",
        "融资阶段、金额与估值：未知",
        "公开联系方式：待人工核验"
      ],
      "nextAction": "打开来源，先确认公司主体、主要经营地、AI 相关性与是否存在可验证融资 / 产品信息。",
      "sources": [
        {
          "title": "量子位 RSS（国内 AI 新闻）",
          "url": "https://www.qbitai.com/2026/07/452942.html",
          "type": "公开新闻 / RSS"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 4,
        "relevance": 4,
        "completeness": 1,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    }
  ],
  "eventCandidates": [
    {
      "id": "live-event-r3b2rb",
      "kind": "event",
      "name": "2026 《AI人工智能大赛案例场景选拔赛》开始！",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：北京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/6853710794500",
      "publishedAt": "06/23 周二 ~ 07/25 周六（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 北京 AI 公开目录收录。主办方：维权365；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "06/23 周二 ~ 07/25 周六（活动行列表页，年份待核验）",
        "location": "北京丰台",
        "mode": "线下 / 待核验",
        "organizer": "维权365"
      },
      "sources": [
        {
          "title": "活动行：北京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/6853710794500",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-14sodkm",
      "kind": "event",
      "name": "8月15日 深度解读《麦肯锡——2026年AI驱动组织现状报告》，拥抱AI时代【线上+线下】",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：北京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/6868278181500",
      "publishedAt": "08/15 周六 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 北京 AI 公开目录收录。主办方：智九人工智能梦想社区；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/15 周六 14:00（活动行列表页，年份待核验）",
        "location": "北京朝阳",
        "mode": "线下 / 待核验",
        "organizer": "智九人工智能梦想社区"
      },
      "sources": [
        {
          "title": "活动行：北京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/6868278181500",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-122c451",
      "kind": "event",
      "name": "企业级AI项目沟通会：世界人工智能大会可落地的AI项目【上海】",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/1869961296600",
      "publishedAt": "07/21 周二 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：司马阅；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/21 周二 14:00（活动行列表页，年份待核验）",
        "location": "上海黄浦",
        "mode": "线下 / 待核验",
        "organizer": "司马阅"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/1869961296600",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-rofnbv",
      "kind": "event",
      "name": "AI产业出海峰会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/2865826950400",
      "publishedAt": "07/30 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：扬帆出海；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/30 周四 14:00（活动行列表页，年份待核验）",
        "location": "上海浦东",
        "mode": "线下 / 待核验",
        "organizer": "扬帆出海"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2865826950400",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1s0t585",
      "kind": "event",
      "name": "EBC 2026 具身智能与人形机器人智脑科技大会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/3867520739300",
      "publishedAt": "09/18 周五 09:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：上海深行智能科技有限公司；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "09/18 周五 09:00（活动行列表页，年份待核验）",
        "location": "上海杨浦",
        "mode": "线下 / 待核验",
        "organizer": "上海深行智能科技有限公司"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/3867520739300",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1n94sdu",
      "kind": "event",
      "name": "2026深圳物联网展-人工智能|机器人|AI|芯片|大模型|智能制造|通信定位|智慧商显|RFID等",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/9868330830000",
      "publishedAt": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：探世展览；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "探世展览"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9868330830000",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-13rkyre",
      "kind": "event",
      "name": "(已成）（深圳）codex、AI-Agent智能体创客交流，AI＋社群应用，各行业应用场景",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/6868998227311",
      "publishedAt": "明天 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：草莓小饼干；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "明天 14:00（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "草莓小饼干"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/6868998227311",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1f9cbub",
      "kind": "event",
      "name": "【AI实战派】网易智企2026企业AI Agent规模化落地峰会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：杭州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/2868441463100",
      "publishedAt": "07/30 周四 13:30（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 杭州 AI 公开目录收录。主办方：网易智企；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/30 周四 13:30（活动行列表页，年份待核验）",
        "location": "浙江杭州",
        "mode": "线下 / 待核验",
        "organizer": "网易智企"
      },
      "sources": [
        {
          "title": "活动行：杭州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2868441463100",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-l5g7z1",
      "kind": "event",
      "name": "AI短剧出海精品沙龙 · 从内容量产到全球盈利的实战闭环",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：杭州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/6870007552711",
      "publishedAt": "08/18 周二 13:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 杭州 AI 公开目录收录。主办方：游戏客栈隋新岩；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/18 周二 13:00（活动行列表页，年份待核验）",
        "location": "浙江杭州",
        "mode": "线下 / 待核验",
        "organizer": "游戏客栈隋新岩"
      },
      "sources": [
        {
          "title": "活动行：杭州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/6870007552711",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1wdh429",
      "kind": "event",
      "name": "第十届全球跨境电商峰会暨2026全球化新品牌AI竞争力大会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：杭州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%9D%AD%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/6867826744300",
      "publishedAt": "07/23 周四 09:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 杭州 AI 公开目录收录。主办方：亿邦动力网；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 09:00（活动行列表页，年份待核验）",
        "location": "浙江杭州",
        "mode": "线下 / 待核验",
        "organizer": "亿邦动力网"
      },
      "sources": [
        {
          "title": "活动行：杭州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/6867826744300",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1x5tpx2",
      "kind": "event",
      "name": "2026大湾区具身智能机器人产业大会暨展览会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：广州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%B9%BF%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/9862767310100",
      "publishedAt": "10/21 周三 ~ 10/23 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 广州 AI 公开目录收录。主办方：ExpoPro；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "10/21 周三 ~ 10/23 周五（活动行列表页，年份待核验）",
        "location": "广东广州",
        "mode": "线下 / 待核验",
        "organizer": "ExpoPro"
      },
      "sources": [
        {
          "title": "活动行：广州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9862767310100",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1opz2ez",
      "kind": "event",
      "name": "四川外贸出海第一课｜成都工厂创业者AI跨境实战分享会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：成都 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%88%90%E9%83%BD&tag=AI",
      "url": "https://www.huodongxing.com/event/9869674477200",
      "publishedAt": "07/22 周三 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 成都 AI 公开目录收录。主办方：外贸牛牛；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/22 周三 14:00（活动行列表页，年份待核验）",
        "location": "四川成都",
        "mode": "线下 / 待核验",
        "organizer": "外贸牛牛"
      },
      "sources": [
        {
          "title": "活动行：成都 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9869674477200",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-wywd95",
      "kind": "event",
      "name": "AI获客增长私房课｜用AI不烧钱，让客户主动找你",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：成都 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%88%90%E9%83%BD&tag=AI",
      "url": "https://www.huodongxing.com/event/8868709069011",
      "publishedAt": "07/23 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 成都 AI 公开目录收录。主办方：杨皓然商业营销；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 14:00（活动行列表页，年份待核验）",
        "location": "四川成都",
        "mode": "线下 / 待核验",
        "organizer": "杨皓然商业营销"
      },
      "sources": [
        {
          "title": "活动行：成都 AI 活动目录",
          "url": "https://www.huodongxing.com/event/8868709069011",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-y04ej5",
      "kind": "event",
      "name": "《智造名城：“人工智能+制造业”背景下，探讨组织与个人的机遇及竞争力》系列读书沙龙",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：南京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8D%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/5869454775500",
      "publishedAt": "09/02 周三 ~ 10/31 周六（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 南京 AI 公开目录收录。主办方：智熵产经智库；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "09/02 周三 ~ 10/31 周六（活动行列表页，年份待核验）",
        "location": "江苏南京",
        "mode": "线下 / 待核验",
        "organizer": "智熵产经智库"
      },
      "sources": [
        {
          "title": "活动行：南京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/5869454775500",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-133sahk",
      "kind": "event",
      "name": "企业家AI第一课 | 让AI成为你的新增长引擎：精准获客、爆款转化、团队复制增长",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：南京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8D%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/8868563402600",
      "publishedAt": "07/29 周三 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 南京 AI 公开目录收录。主办方：腾讯众创空间（南京）；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/29 周三 14:00（活动行列表页，年份待核验）",
        "location": "江苏南京",
        "mode": "线下 / 待核验",
        "organizer": "腾讯众创空间（南京）"
      },
      "sources": [
        {
          "title": "活动行：南京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/8868563402600",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-ac26lv",
      "kind": "event",
      "name": "2026莲花山人工智能大会暨“7·22鄂州人才周”AI+生物医药产业发展大会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：武汉 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%AD%A6%E6%B1%89&tag=AI",
      "url": "https://www.huodongxing.com/event/7869144244600",
      "publishedAt": "07/23 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 武汉 AI 公开目录收录。主办方：光谷创业咖啡；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 14:00（活动行列表页，年份待核验）",
        "location": "湖北武汉",
        "mode": "线下 / 待核验",
        "organizer": "光谷创业咖啡"
      },
      "sources": [
        {
          "title": "活动行：武汉 AI 活动目录",
          "url": "https://www.huodongxing.com/event/7869144244600",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-l0z6vu",
      "kind": "event",
      "name": "AI超级组织10倍增长私享会 ——OPC一人公司 × OPD一人部门 × FDE前沿部署企业增长实践",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：武汉 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%AD%A6%E6%B1%89&tag=AI",
      "url": "https://www.huodongxing.com/event/6869607764900",
      "publishedAt": "今天 13:30（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 武汉 AI 公开目录收录。主办方：智能体来了；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "今天 13:30（活动行列表页，年份待核验）",
        "location": "湖北武汉",
        "mode": "线下 / 待核验",
        "organizer": "智能体来了"
      },
      "sources": [
        {
          "title": "活动行：武汉 AI 活动目录",
          "url": "https://www.huodongxing.com/event/6869607764900",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-7gw7o9",
      "kind": "event",
      "name": "《智造之城：“人工智能+制造业”背景下，探讨组织与个人的机遇及竞争力》系列读书沙龙",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：苏州 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E8%8B%8F%E5%B7%9E&tag=AI",
      "url": "https://www.huodongxing.com/event/5869601989211",
      "publishedAt": "09/19 周六 ~ 11/21 周六（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 苏州 AI 公开目录收录。主办方：智熵产经智库；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "09/19 周六 ~ 11/21 周六（活动行列表页，年份待核验）",
        "location": "江苏苏州",
        "mode": "线下 / 待核验",
        "organizer": "智熵产经智库"
      },
      "sources": [
        {
          "title": "活动行：苏州 AI 活动目录",
          "url": "https://www.huodongxing.com/event/5869601989211",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-gihn16",
      "kind": "event",
      "name": "西安市《视播时代企业短视频+AI获客》总裁班",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：西安 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E8%A5%BF%E5%AE%89&tag=AI",
      "url": "https://www.huodongxing.com/event/4867724262611",
      "publishedAt": "07/21 周二 ~ 07/23 周四（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 西安 AI 公开目录收录。主办方：和君咨询集团股份有限公司；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/21 周二 ~ 07/23 周四（活动行列表页，年份待核验）",
        "location": "陕西西安",
        "mode": "线下 / 待核验",
        "organizer": "和君咨询集团股份有限公司"
      },
      "sources": [
        {
          "title": "活动行：西安 AI 活动目录",
          "url": "https://www.huodongxing.com/event/4867724262611",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1l3inyv",
      "kind": "event",
      "name": "西安青少年·AI黑客松·一日实战营（2日2场）",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：西安 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E8%A5%BF%E5%AE%89&tag=AI",
      "url": "https://www.huodongxing.com/event/9869867388500",
      "publishedAt": "07/25 周六 ~ 07/26 周日（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 西安 AI 公开目录收录。主办方：AI黄埔学院；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/25 周六 ~ 07/26 周日（活动行列表页，年份待核验）",
        "location": "陕西西安",
        "mode": "线下 / 待核验",
        "organizer": "AI黄埔学院"
      },
      "sources": [
        {
          "title": "活动行：西安 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9869867388500",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1jqb03h",
      "kind": "event",
      "name": "重庆市《视播时代企业短视频+AI获客》总裁班",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：重庆 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E9%87%8D%E5%BA%86&tag=AI",
      "url": "https://www.huodongxing.com/event/8869685875511",
      "publishedAt": "07/22 周三 09:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 重庆 AI 公开目录收录。主办方：重庆东方紫荆国际教育有限公司；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/22 周三 09:00（活动行列表页，年份待核验）",
        "location": "重庆江北",
        "mode": "线下 / 待核验",
        "organizer": "重庆东方紫荆国际教育有限公司"
      },
      "sources": [
        {
          "title": "活动行：重庆 AI 活动目录",
          "url": "https://www.huodongxing.com/event/8869685875511",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-423h00",
      "kind": "event",
      "name": "AI 时代，普通人如何开始一人公司？｜OPC同行社 Coffee Chat 天津站",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：天津 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%A4%A9%E6%B4%A5&tag=AI",
      "url": "https://www.huodongxing.com/event/8870035078811",
      "publishedAt": "08/01 周六 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 天津 AI 公开目录收录。主办方：OPC同行社；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/01 周六 14:00（活动行列表页，年份待核验）",
        "location": "天津河东",
        "mode": "线下 / 待核验",
        "organizer": "OPC同行社"
      },
      "sources": [
        {
          "title": "活动行：天津 AI 活动目录",
          "url": "https://www.huodongxing.com/event/8870035078811",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1szbgy8",
      "kind": "event",
      "name": "长沙市《视播时代企业短视频+AI获客》总裁班",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：长沙 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E9%95%BF%E6%B2%99&tag=AI",
      "url": "https://www.huodongxing.com/event/2867443810711",
      "publishedAt": "07/18 周六 ~ 07/20 周一（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 长沙 AI 公开目录收录。主办方：重庆东方紫荆国际教育有限公司；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/18 周六 ~ 07/20 周一（活动行列表页，年份待核验）",
        "location": "湖南长沙",
        "mode": "线下 / 待核验",
        "organizer": "重庆东方紫荆国际教育有限公司"
      },
      "sources": [
        {
          "title": "活动行：长沙 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2867443810711",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1gruzxt",
      "kind": "event",
      "name": "AI全域获客之企业增长沙龙",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：长沙 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E9%95%BF%E6%B2%99&tag=AI",
      "url": "https://www.huodongxing.com/event/7869176342200",
      "publishedAt": "07/16 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 长沙 AI 公开目录收录。主办方：长沙清风寨电子商务有限公司；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/16 周四 14:00（活动行列表页，年份待核验）",
        "location": "湖南长沙",
        "mode": "线下 / 待核验",
        "organizer": "长沙清风寨电子商务有限公司"
      },
      "sources": [
        {
          "title": "活动行：长沙 AI 活动目录",
          "url": "https://www.huodongxing.com/event/7869176342200",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-114hoxp",
      "kind": "event",
      "name": "2026 ‘AI+制造’ 赋能安徽专精特新企业高质量发展大会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：合肥 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%90%88%E8%82%A5&tag=AI",
      "url": "https://www.huodongxing.com/event/4863781353900",
      "publishedAt": "07/24 周五 09:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 合肥 AI 公开目录收录。主办方：科技达人；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/24 周五 09:00（活动行列表页，年份待核验）",
        "location": "安徽合肥",
        "mode": "线下 / 待核验",
        "organizer": "科技达人"
      },
      "sources": [
        {
          "title": "活动行：合肥 AI 活动目录",
          "url": "https://www.huodongxing.com/event/4863781353900",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-uq0yc2",
      "kind": "event",
      "name": "AI 重构获客新周期 GEO 生成式引擎优化行业 沙龙会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：厦门 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8E%A6%E9%97%A8&tag=AI",
      "url": "https://www.huodongxing.com/event/7869678109500",
      "publishedAt": "今天 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 厦门 AI 公开目录收录。主办方：结伴学AI教育 厦门运营中心；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "今天 14:00（活动行列表页，年份待核验）",
        "location": "福建厦门",
        "mode": "线下 / 待核验",
        "organizer": "结伴学AI教育 厦门运营中心"
      },
      "sources": [
        {
          "title": "活动行：厦门 AI 活动目录",
          "url": "https://www.huodongxing.com/event/7869678109500",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-wuzkgq",
      "kind": "event",
      "name": "OPC x AI x 流量 = 变现｜OPC同行社 Coffee Chat 厦门站",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：厦门 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8E%A6%E9%97%A8&tag=AI",
      "url": "https://www.huodongxing.com/event/7869540558500",
      "publishedAt": "07/26 周日 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 厦门 AI 公开目录收录。主办方：OPC同行社；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/26 周日 14:00（活动行列表页，年份待核验）",
        "location": "福建厦门",
        "mode": "线下 / 待核验",
        "organizer": "OPC同行社"
      },
      "sources": [
        {
          "title": "活动行：厦门 AI 活动目录",
          "url": "https://www.huodongxing.com/event/7869540558500",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-dnim6s",
      "kind": "event",
      "name": "青岛站《企业短视频+AI获客策略精华班》开课通知",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：青岛 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E9%9D%92%E5%B2%9B&tag=AI",
      "url": "https://www.huodongxing.com/event/1867728036211",
      "publishedAt": "07/27 周一 ~ 07/29 周三（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-18T05:39:05.705Z",
      "summary": "活动行 青岛 AI 公开目录收录。主办方：博君企业管理咨询集团股份有限公司；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/27 周一 ~ 07/29 周三（活动行列表页，年份待核验）",
        "location": "山东青岛",
        "mode": "线下 / 待核验",
        "organizer": "博君企业管理咨询集团股份有限公司"
      },
      "sources": [
        {
          "title": "活动行：青岛 AI 活动目录",
          "url": "https://www.huodongxing.com/event/1867728036211",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "firstCollectedAt": "2026-07-18T05:16:14.220Z",
      "lastSeenAt": "2026-07-18T05:39:05.705Z",
      "seenCount": 2,
      "isNew": false
    },
    {
      "id": "live-event-1346qhn",
      "kind": "event",
      "name": "AI之后，应用如何增长？ ----非游出海实践闭门分享",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：北京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/9868437057000",
      "publishedAt": "07/23 周四 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 北京 AI 公开目录收录。主办方：麦炽；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/23 周四 14:00（活动行列表页，年份待核验）",
        "location": "北京海淀",
        "mode": "线下 / 待核验",
        "organizer": "麦炽"
      },
      "sources": [
        {
          "title": "活动行：北京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/9868437057000",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-event-1tovguz",
      "kind": "event",
      "name": "AI引爆营销—纯公益分享",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：北京 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E5%8C%97%E4%BA%AC&tag=AI",
      "url": "https://www.huodongxing.com/event/4869998006000",
      "publishedAt": "07/25 周六 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 北京 AI 公开目录收录。主办方：锦上AIOPC创业孵化平台；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/25 周六 14:00（活动行列表页，年份待核验）",
        "location": "北京丰台",
        "mode": "线下 / 待核验",
        "organizer": "锦上AIOPC创业孵化平台"
      },
      "sources": [
        {
          "title": "活动行：北京 AI 活动目录",
          "url": "https://www.huodongxing.com/event/4869998006000",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-event-kyy7qu",
      "kind": "event",
      "name": "BEYOND Expo-人工智能创新主题沙龙",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/2869421440200",
      "publishedAt": "07/31 周五 13:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：动点科技 TechNode；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/31 周五 13:00（活动行列表页，年份待核验）",
        "location": "上海浦东",
        "mode": "线下 / 待核验",
        "organizer": "动点科技 TechNode"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/2869421440200",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-event-14n7fmf",
      "kind": "event",
      "name": "WAIC世界人工智能大会Afterparty|AI ICON标杆聚会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：上海 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E4%B8%8A%E6%B5%B7&tag=AI",
      "url": "https://www.huodongxing.com/event/8869251381200",
      "publishedAt": "07/20 周一 18:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 上海 AI 公开目录收录。主办方：NexusTech；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/20 周一 18:00（活动行列表页，年份待核验）",
        "location": "上海徐汇",
        "mode": "线下 / 待核验",
        "organizer": "NexusTech"
      },
      "sources": [
        {
          "title": "活动行：上海 AI 活动目录",
          "url": "https://www.huodongxing.com/event/8869251381200",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-event-14p6vw6",
      "kind": "event",
      "name": "AGIC2026深圳人工智能展",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/5859922218300",
      "publishedAt": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：世界人工智能与物联网创新联盟（WAIA）；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/26 周三 ~ 08/28 周五（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "世界人工智能与物联网创新联盟（WAIA）"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/5859922218300",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-event-z4hyq8",
      "kind": "event",
      "name": "【邀请函】走进众擎机器人总部-蜗牛工场名企走访第21期",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/4868530661300",
      "publishedAt": "07/22 周三 14:30（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：蜗牛工场；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "07/22 周三 14:30（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "蜗牛工场"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/4868530661300",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-event-10c97j1",
      "kind": "event",
      "name": "2026 AI赋能跨境电商与海外达人合作展览会",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：深圳 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%B7%B1%E5%9C%B3&tag=AI",
      "url": "https://www.huodongxing.com/event/7862775396900",
      "publishedAt": "08/04 周二 ~ 08/05 周三（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 深圳 AI 公开目录收录。主办方：TikTok 卖家门户网TKFFF；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "08/04 周二 ~ 08/05 周三（活动行列表页，年份待核验）",
        "location": "广东深圳",
        "mode": "线下 / 待核验",
        "organizer": "TikTok 卖家门户网TKFFF"
      },
      "sources": [
        {
          "title": "活动行：深圳 AI 活动目录",
          "url": "https://www.huodongxing.com/event/7862775396900",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    },
    {
      "id": "live-event-1p73ok1",
      "kind": "event",
      "name": "成都｜AI与多资产交易的未来",
      "category": "国内 AI 活动待核验",
      "sourceName": "活动行：成都 AI 活动目录",
      "sourceUrl": "https://www.huodongxing.com/events?city=%E6%88%90%E9%83%BD&tag=AI",
      "url": "https://www.huodongxing.com/event/1868452013100",
      "publishedAt": "后天 14:00（活动行列表页，年份待核验）",
      "collectedAt": "2026-07-17T14:05:36.682Z",
      "summary": "活动行 成都 AI 公开目录收录。主办方：123X Labs；具体议程、嘉宾与项目展示需打开活动页核验。",
      "confidence": "待核验",
      "reasoning": "规则命中：国内优先公开源、AI 相关关键词、国内 AI 活动目录；活动质量、嘉宾、主办方和项目发现价值均未由 Agent 自动确认。",
      "unknowns": [
        "主办方、嘉宾和实际参与人群：待核验",
        "活动质量与项目发现价值：待人工筛选",
        "公开联系入口：请以来源页为准"
      ],
      "nextAction": "打开活动页，确认日期、主办方、嘉宾与是否存在创业者交流或项目展示机制。",
      "eventMeta": {
        "startDate": "后天 14:00（活动行列表页，年份待核验）",
        "location": "四川成都",
        "mode": "线下 / 待核验",
        "organizer": "123X Labs"
      },
      "sources": [
        {
          "title": "活动行：成都 AI 活动目录",
          "url": "https://www.huodongxing.com/event/1868452013100",
          "type": "公开活动目录"
        }
      ],
      "score": {
        "novelty": 5,
        "source": 3,
        "relevance": 4,
        "completeness": 2,
        "followup": 4
      },
      "isNew": false,
      "firstCollectedAt": "2026-07-17T14:05:36.682Z",
      "lastSeenAt": "2026-07-17T14:05:36.682Z",
      "seenCount": 1
    }
  ]
};
})();
